{
  "uid" : "21852fd6b7e5c6cf",
  "name" : "Verify composition, visibility of elements on the 1st-6th levels of nesting on the page",
  "fullName" : "tests.groups_page_test.TestGroupsPageStructure#test_gp_01_02_verify_page_structure_and_visibility",
  "historyId" : "bcc02f9e01a0ed01e27b29f6fd9271c0",
  "time" : {
    "start" : 1728608174497,
    "stop" : 1728608174497,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x5595cde6502a <unknown>\n#1 0x5595cdb4b5e0 <unknown>\n#2 0x5595cdb437eb <unknown>\n#3 0x5595cdb33a09 <unknown>\n#4 0x5595cdb35744 <unknown>\n#5 0x5595cdb33cbd <unknown>\n#6 0x5595cdb3352f <unknown>\n#7 0x5595cdb33422 <unknown>\n#8 0x5595cdb31493 <unknown>\n#9 0x5595cdb31ada <unknown>\n#10 0x5595cdb4df41 <unknown>\n#11 0x5595cdbdf8c5 <unknown>\n#12 0x5595cdbbfb22 <unknown>\n#13 0x5595cdbded7d <unknown>\n#14 0x5595cdbbf8c3 <unknown>\n#15 0x5595cdb8d6b3 <unknown>\n#16 0x5595cdb8e68e <unknown>\n#17 0x5595cde2fa2b <unknown>\n#18 0x5595cde339b1 <unknown>\n#19 0x5595cde1c225 <unknown>\n#20 0x5595cde34532 <unknown>\n#21 0x5595cde0138f <unknown>\n#22 0x5595cde53f28 <unknown>\n#23 0x5595cde540f3 <unknown>\n#24 0x5595cde63e7c <unknown>\n#25 0x7f2f38e94ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"b7f9da04ac92cd4fe4a783f9f439618e\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fb25e43f8c0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x5595cde540f3 \\\\u003Cunknown>\\\\n#24 0x5595cde63e7c \\\\u003Cunknown>\\\\n#25 0x7f2f38e94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x5595cde6502a <unknown>\nE       #1 0x5595cdb4b5e0 <unknown>\nE       #2 0x5595cdb437eb <unknown>\nE       #3 0x5595cdb33a09 <unknown>\nE       #4 0x5595cdb35744 <unknown>\nE       #5 0x5595cdb33cbd <unknown>\nE       #6 0x5595cdb3352f <unknown>\nE       #7 0x5595cdb33422 <unknown>\nE       #8 0x5595cdb31493 <unknown>\nE       #9 0x5595cdb31ada <unknown>\nE       #10 0x5595cdb4df41 <unknown>\nE       #11 0x5595cdbdf8c5 <unknown>\nE       #12 0x5595cdbbfb22 <unknown>\nE       #13 0x5595cdbded7d <unknown>\nE       #14 0x5595cdbbf8c3 <unknown>\nE       #15 0x5595cdb8d6b3 <unknown>\nE       #16 0x5595cdb8e68e <unknown>\nE       #17 0x5595cde2fa2b <unknown>\nE       #18 0x5595cde339b1 <unknown>\nE       #19 0x5595cde1c225 <unknown>\nE       #20 0x5595cde34532 <unknown>\nE       #21 0x5595cde0138f <unknown>\nE       #22 0x5595cde53f28 <unknown>\nE       #23 0x5595cde540f3 <unknown>\nE       #24 0x5595cde63e7c <unknown>\nE       #25 0x7f2f38e94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "driver",
    "time" : {
      "start" : 1728608174497,
      "stop" : 1728608175268,
      "duration" : 771
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728608130626,
      "stop" : 1728608130626,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728608175269,
      "stop" : 1728608175753,
      "duration" : 484
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x5595cde6502a <unknown>\n#1 0x5595cdb4b5e0 <unknown>\n#2 0x5595cdb437eb <unknown>\n#3 0x5595cdb33a09 <unknown>\n#4 0x5595cdb35744 <unknown>\n#5 0x5595cdb33cbd <unknown>\n#6 0x5595cdb3352f <unknown>\n#7 0x5595cdb33422 <unknown>\n#8 0x5595cdb31493 <unknown>\n#9 0x5595cdb31ada <unknown>\n#10 0x5595cdb4df41 <unknown>\n#11 0x5595cdbdf8c5 <unknown>\n#12 0x5595cdbbfb22 <unknown>\n#13 0x5595cdbded7d <unknown>\n#14 0x5595cdbbf8c3 <unknown>\n#15 0x5595cdb8d6b3 <unknown>\n#16 0x5595cdb8e68e <unknown>\n#17 0x5595cde2fa2b <unknown>\n#18 0x5595cde339b1 <unknown>\n#19 0x5595cde1c225 <unknown>\n#20 0x5595cde34532 <unknown>\n#21 0x5595cde0138f <unknown>\n#22 0x5595cde53f28 <unknown>\n#23 0x5595cde540f3 <unknown>\n#24 0x5595cde63e7c <unknown>\n#25 0x7f2f38e94ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728608175269,
        "stop" : 1728608175753,
        "duration" : 484
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x5595cde6502a <unknown>\n#1 0x5595cdb4b5e0 <unknown>\n#2 0x5595cdb437eb <unknown>\n#3 0x5595cdb33a09 <unknown>\n#4 0x5595cdb35744 <unknown>\n#5 0x5595cdb33cbd <unknown>\n#6 0x5595cdb3352f <unknown>\n#7 0x5595cdb33422 <unknown>\n#8 0x5595cdb31493 <unknown>\n#9 0x5595cdb31ada <unknown>\n#10 0x5595cdb4df41 <unknown>\n#11 0x5595cdbdf8c5 <unknown>\n#12 0x5595cdbbfb22 <unknown>\n#13 0x5595cdbded7d <unknown>\n#14 0x5595cdbbf8c3 <unknown>\n#15 0x5595cdb8d6b3 <unknown>\n#16 0x5595cdb8e68e <unknown>\n#17 0x5595cde2fa2b <unknown>\n#18 0x5595cde339b1 <unknown>\n#19 0x5595cde1c225 <unknown>\n#20 0x5595cde34532 <unknown>\n#21 0x5595cde0138f <unknown>\n#22 0x5595cde53f28 <unknown>\n#23 0x5595cde540f3 <unknown>\n#24 0x5595cde63e7c <unknown>\n#25 0x7f2f38e94ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"b7f9da04ac92cd4fe4a783f9f439618e\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728608175784,
      "stop" : 1728608175846,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "The Groups Page"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "groups_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestGroupsPage"
  }, {
    "name" : "host",
    "value" : "fv-az523-260"
  }, {
    "name" : "thread",
    "value" : "2358-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.groups_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 1,
        "skipped" : 0,
        "passed" : 8,
        "unknown" : 0,
        "total" : 9
      },
      "items" : [ {
        "uid" : "eb4c6f34387b7194",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/322//#testresult/eb4c6f34387b7194",
        "status" : "passed",
        "time" : {
          "start" : 1728556908853,
          "stop" : 1728556910129,
          "duration" : 1276
        }
      }, {
        "uid" : "2a13e5d26775c2c2",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/321//#testresult/2a13e5d26775c2c2",
        "status" : "passed",
        "time" : {
          "start" : 1728553832527,
          "stop" : 1728553833792,
          "duration" : 1265
        }
      }, {
        "uid" : "e3269d3234bfbc6c",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/148//#testresult/e3269d3234bfbc6c",
        "status" : "passed",
        "time" : {
          "start" : 1728521936971,
          "stop" : 1728521938272,
          "duration" : 1301
        }
      }, {
        "uid" : "cb3449b61e84cdc",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/320//#testresult/cb3449b61e84cdc",
        "status" : "passed",
        "time" : {
          "start" : 1728470394891,
          "stop" : 1728470396170,
          "duration" : 1279
        }
      }, {
        "uid" : "c5f63236af736f40",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/319//#testresult/c5f63236af736f40",
        "status" : "passed",
        "time" : {
          "start" : 1728467806695,
          "stop" : 1728467807967,
          "duration" : 1272
        }
      }, {
        "uid" : "dd0649519064b0e6",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/147//#testresult/dd0649519064b0e6",
        "status" : "passed",
        "time" : {
          "start" : 1728435655882,
          "stop" : 1728435655973,
          "duration" : 91
        }
      }, {
        "uid" : "9552edb4630009dc",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/318//#testresult/9552edb4630009dc",
        "status" : "passed",
        "time" : {
          "start" : 1728377916237,
          "stop" : 1728377916328,
          "duration" : 91
        }
      }, {
        "uid" : "b3cb65352eca56b3",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/317//#testresult/b3cb65352eca56b3",
        "status" : "passed",
        "time" : {
          "start" : 1728375118907,
          "stop" : 1728375118991,
          "duration" : 84
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "21852fd6b7e5c6cf.json",
  "parameterValues" : [ ]
}