{
  "uid" : "32f927e1e6516dff",
  "name" : "Verify redirection to specialists page not authorized user.",
  "fullName" : "tests.description_page_test.TestDescriptionPage#test_dp_05_verify_redirection_to_specialists_page",
  "historyId" : "2bb438cf0156f1b8aed1660bcc15d225",
  "time" : {
    "start" : 1728694537575,
    "stop" : 1728694537575,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55e6373c302a <unknown>\n#1 0x55e6370a95e0 <unknown>\n#2 0x55e6370a17eb <unknown>\n#3 0x55e637091a09 <unknown>\n#4 0x55e637093744 <unknown>\n#5 0x55e637091cbd <unknown>\n#6 0x55e63709152f <unknown>\n#7 0x55e637091422 <unknown>\n#8 0x55e63708f493 <unknown>\n#9 0x55e63708fada <unknown>\n#10 0x55e6370abf41 <unknown>\n#11 0x55e63713d8c5 <unknown>\n#12 0x55e63711db22 <unknown>\n#13 0x55e63713cd7d <unknown>\n#14 0x55e63711d8c3 <unknown>\n#15 0x55e6370eb6b3 <unknown>\n#16 0x55e6370ec68e <unknown>\n#17 0x55e63738da2b <unknown>\n#18 0x55e6373919b1 <unknown>\n#19 0x55e63737a225 <unknown>\n#20 0x55e637392532 <unknown>\n#21 0x55e63735f38f <unknown>\n#22 0x55e6373b1f28 <unknown>\n#23 0x55e6373b20f3 <unknown>\n#24 0x55e6373c1e7c <unknown>\n#25 0x7ff4c9694ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"20fdadb1fea718c8dafb40d9a2a4f907\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f8f5b519d30>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x55e6373b20f3 \\\\u003Cunknown>\\\\n#24 0x55e6373c1e7c \\\\u003Cunknown>\\\\n#25 0x7ff4c9694ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x55e6373c302a <unknown>\nE       #1 0x55e6370a95e0 <unknown>\nE       #2 0x55e6370a17eb <unknown>\nE       #3 0x55e637091a09 <unknown>\nE       #4 0x55e637093744 <unknown>\nE       #5 0x55e637091cbd <unknown>\nE       #6 0x55e63709152f <unknown>\nE       #7 0x55e637091422 <unknown>\nE       #8 0x55e63708f493 <unknown>\nE       #9 0x55e63708fada <unknown>\nE       #10 0x55e6370abf41 <unknown>\nE       #11 0x55e63713d8c5 <unknown>\nE       #12 0x55e63711db22 <unknown>\nE       #13 0x55e63713cd7d <unknown>\nE       #14 0x55e63711d8c3 <unknown>\nE       #15 0x55e6370eb6b3 <unknown>\nE       #16 0x55e6370ec68e <unknown>\nE       #17 0x55e63738da2b <unknown>\nE       #18 0x55e6373919b1 <unknown>\nE       #19 0x55e63737a225 <unknown>\nE       #20 0x55e637392532 <unknown>\nE       #21 0x55e63735f38f <unknown>\nE       #22 0x55e6373b1f28 <unknown>\nE       #23 0x55e6373b20f3 <unknown>\nE       #24 0x55e6373c1e7c <unknown>\nE       #25 0x7ff4c9694ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "driver",
    "time" : {
      "start" : 1728694537575,
      "stop" : 1728694538356,
      "duration" : 781
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728694482412,
      "stop" : 1728694482412,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728694538357,
      "stop" : 1728694538998,
      "duration" : 641
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55e6373c302a <unknown>\n#1 0x55e6370a95e0 <unknown>\n#2 0x55e6370a17eb <unknown>\n#3 0x55e637091a09 <unknown>\n#4 0x55e637093744 <unknown>\n#5 0x55e637091cbd <unknown>\n#6 0x55e63709152f <unknown>\n#7 0x55e637091422 <unknown>\n#8 0x55e63708f493 <unknown>\n#9 0x55e63708fada <unknown>\n#10 0x55e6370abf41 <unknown>\n#11 0x55e63713d8c5 <unknown>\n#12 0x55e63711db22 <unknown>\n#13 0x55e63713cd7d <unknown>\n#14 0x55e63711d8c3 <unknown>\n#15 0x55e6370eb6b3 <unknown>\n#16 0x55e6370ec68e <unknown>\n#17 0x55e63738da2b <unknown>\n#18 0x55e6373919b1 <unknown>\n#19 0x55e63737a225 <unknown>\n#20 0x55e637392532 <unknown>\n#21 0x55e63735f38f <unknown>\n#22 0x55e6373b1f28 <unknown>\n#23 0x55e6373b20f3 <unknown>\n#24 0x55e6373c1e7c <unknown>\n#25 0x7ff4c9694ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728694538357,
        "stop" : 1728694538998,
        "duration" : 641
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55e6373c302a <unknown>\n#1 0x55e6370a95e0 <unknown>\n#2 0x55e6370a17eb <unknown>\n#3 0x55e637091a09 <unknown>\n#4 0x55e637093744 <unknown>\n#5 0x55e637091cbd <unknown>\n#6 0x55e63709152f <unknown>\n#7 0x55e637091422 <unknown>\n#8 0x55e63708f493 <unknown>\n#9 0x55e63708fada <unknown>\n#10 0x55e6370abf41 <unknown>\n#11 0x55e63713d8c5 <unknown>\n#12 0x55e63711db22 <unknown>\n#13 0x55e63713cd7d <unknown>\n#14 0x55e63711d8c3 <unknown>\n#15 0x55e6370eb6b3 <unknown>\n#16 0x55e6370ec68e <unknown>\n#17 0x55e63738da2b <unknown>\n#18 0x55e6373919b1 <unknown>\n#19 0x55e63737a225 <unknown>\n#20 0x55e637392532 <unknown>\n#21 0x55e63735f38f <unknown>\n#22 0x55e6373b1f28 <unknown>\n#23 0x55e6373b20f3 <unknown>\n#24 0x55e6373c1e7c <unknown>\n#25 0x7ff4c9694ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"20fdadb1fea718c8dafb40d9a2a4f907\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728694539030,
      "stop" : 1728694539092,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Description Page."
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "description_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestDescriptionPage"
  }, {
    "name" : "host",
    "value" : "fv-az1245-423"
  }, {
    "name" : "thread",
    "value" : "2340-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.description_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 10,
        "skipped" : 0,
        "passed" : 488,
        "unknown" : 0,
        "total" : 498
      },
      "items" : [ {
        "uid" : "6edc60c4542e3175",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/149//#testresult/6edc60c4542e3175",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55bb2361c02a <unknown>\n#1 0x55bb233025e0 <unknown>\n#2 0x55bb232fa7eb <unknown>\n#3 0x55bb232eaa09 <unknown>\n#4 0x55bb232ec744 <unknown>\n#5 0x55bb232eacbd <unknown>\n#6 0x55bb232ea52f <unknown>\n#7 0x55bb232ea422 <unknown>\n#8 0x55bb232e8493 <unknown>\n#9 0x55bb232e8ada <unknown>\n#10 0x55bb23304f41 <unknown>\n#11 0x55bb233968c5 <unknown>\n#12 0x55bb23376b22 <unknown>\n#13 0x55bb23395d7d <unknown>\n#14 0x55bb233768c3 <unknown>\n#15 0x55bb233446b3 <unknown>\n#16 0x55bb2334568e <unknown>\n#17 0x55bb235e6a2b <unknown>\n#18 0x55bb235ea9b1 <unknown>\n#19 0x55bb235d3225 <unknown>\n#20 0x55bb235eb532 <unknown>\n#21 0x55bb235b838f <unknown>\n#22 0x55bb2360af28 <unknown>\n#23 0x55bb2360b0f3 <unknown>\n#24 0x55bb2361ae7c <unknown>\n#25 0x7fae19894ac3 <unknown>",
        "time" : {
          "start" : 1728608154345,
          "stop" : 1728608154345,
          "duration" : 0
        }
      }, {
        "uid" : "d824af215fa686e3",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/322//#testresult/d824af215fa686e3",
        "status" : "passed",
        "time" : {
          "start" : 1728556812857,
          "stop" : 1728556814008,
          "duration" : 1151
        }
      }, {
        "uid" : "4e9f2c12cc5ed06",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/321//#testresult/4e9f2c12cc5ed06",
        "status" : "passed",
        "time" : {
          "start" : 1728553746217,
          "stop" : 1728553746883,
          "duration" : 666
        }
      }, {
        "uid" : "a1ef201ca497ef80",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/148//#testresult/a1ef201ca497ef80",
        "status" : "passed",
        "time" : {
          "start" : 1728521839877,
          "stop" : 1728521841038,
          "duration" : 1161
        }
      }, {
        "uid" : "539c982f681786fa",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/320//#testresult/539c982f681786fa",
        "status" : "passed",
        "time" : {
          "start" : 1728470318915,
          "stop" : 1728470320091,
          "duration" : 1176
        }
      }, {
        "uid" : "3030c7286953eb48",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/319//#testresult/3030c7286953eb48",
        "status" : "passed",
        "time" : {
          "start" : 1728467726443,
          "stop" : 1728467727105,
          "duration" : 662
        }
      }, {
        "uid" : "9c1d3574449ba7ea",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/147//#testresult/9c1d3574449ba7ea",
        "status" : "passed",
        "time" : {
          "start" : 1728435437789,
          "stop" : 1728435438952,
          "duration" : 1163
        }
      }, {
        "uid" : "a32f217062a030df",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/318//#testresult/a32f217062a030df",
        "status" : "passed",
        "time" : {
          "start" : 1728377843552,
          "stop" : 1728377844722,
          "duration" : 1170
        }
      }, {
        "uid" : "70d6b2142f0d53b5",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/317//#testresult/70d6b2142f0d53b5",
        "status" : "passed",
        "time" : {
          "start" : 1728375045147,
          "stop" : 1728375045804,
          "duration" : 657
        }
      }, {
        "uid" : "953e42dad02fbe63",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/316//#testresult/953e42dad02fbe63",
        "status" : "passed",
        "time" : {
          "start" : 1728374933733,
          "stop" : 1728374934385,
          "duration" : 652
        }
      }, {
        "uid" : "b3e3f3ede29dfec6",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/146//#testresult/b3e3f3ede29dfec6",
        "status" : "passed",
        "time" : {
          "start" : 1728349022539,
          "stop" : 1728349026718,
          "duration" : 4179
        }
      }, {
        "uid" : "e28e910c993dbc40",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/315//#testresult/e28e910c993dbc40",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/specialists",
        "time" : {
          "start" : 1728292525743,
          "stop" : 1728292566169,
          "duration" : 40426
        }
      }, {
        "uid" : "65b80fbbefb4415a",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/314//#testresult/65b80fbbefb4415a",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/specialists",
        "time" : {
          "start" : 1728289566324,
          "stop" : 1728289606793,
          "duration" : 40469
        }
      }, {
        "uid" : "d2918ed8f872c835",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/145//#testresult/d2918ed8f872c835",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/specialists",
        "time" : {
          "start" : 1728262974168,
          "stop" : 1728263014580,
          "duration" : 40412
        }
      }, {
        "uid" : "1e5659a16c225b8e",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/313//#testresult/1e5659a16c225b8e",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/specialists",
        "time" : {
          "start" : 1728226071873,
          "stop" : 1728226112302,
          "duration" : 40429
        }
      }, {
        "uid" : "3cfce2efa204f850",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/312//#testresult/3cfce2efa204f850",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/specialists",
        "time" : {
          "start" : 1728221221933,
          "stop" : 1728221262384,
          "duration" : 40451
        }
      }, {
        "uid" : "c60ba161ca15b187",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/144//#testresult/c60ba161ca15b187",
        "status" : "passed",
        "time" : {
          "start" : 1728176560342,
          "stop" : 1728176560995,
          "duration" : 653
        }
      }, {
        "uid" : "f076e21414785136",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/311//#testresult/f076e21414785136",
        "status" : "passed",
        "time" : {
          "start" : 1728117231124,
          "stop" : 1728117231801,
          "duration" : 677
        }
      }, {
        "uid" : "438037f241fefb2e",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/310//#testresult/438037f241fefb2e",
        "status" : "passed",
        "time" : {
          "start" : 1728108635581,
          "stop" : 1728108636236,
          "duration" : 655
        }
      }, {
        "uid" : "c69ef2c85c45826c",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/143//#testresult/c69ef2c85c45826c",
        "status" : "passed",
        "time" : {
          "start" : 1728089894917,
          "stop" : 1728089895586,
          "duration" : 669
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "32f927e1e6516dff.json",
  "parameterValues" : [ ]
}