{
  "uid" : "67f606dbb1ffce64",
  "name" : "Verify values of the text in links, buttons in the Header for an unauthorized user",
  "fullName" : "tests.header_test.TestUnauthHeaderPageText#test_hpu_02_01_verify_unauth_text_in_links_and_buttons",
  "historyId" : "34422bb40cdc578b0f7fefa58871fd77",
  "time" : {
    "start" : 1728694567757,
    "stop" : 1728694567757,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55957af5e02a <unknown>\n#1 0x55957ac445e0 <unknown>\n#2 0x55957ac3c7eb <unknown>\n#3 0x55957ac2ca09 <unknown>\n#4 0x55957ac2e744 <unknown>\n#5 0x55957ac2ccbd <unknown>\n#6 0x55957ac2c52f <unknown>\n#7 0x55957ac2c422 <unknown>\n#8 0x55957ac2a493 <unknown>\n#9 0x55957ac2aada <unknown>\n#10 0x55957ac46f41 <unknown>\n#11 0x55957acd88c5 <unknown>\n#12 0x55957acb8b22 <unknown>\n#13 0x55957acd7d7d <unknown>\n#14 0x55957acb88c3 <unknown>\n#15 0x55957ac866b3 <unknown>\n#16 0x55957ac8768e <unknown>\n#17 0x55957af28a2b <unknown>\n#18 0x55957af2c9b1 <unknown>\n#19 0x55957af15225 <unknown>\n#20 0x55957af2d532 <unknown>\n#21 0x55957aefa38f <unknown>\n#22 0x55957af4cf28 <unknown>\n#23 0x55957af4d0f3 <unknown>\n#24 0x55957af5ce7c <unknown>\n#25 0x7f439ba94ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a3ba60c53331bfecf56b11e80818f599\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f8f5b2fb7a0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x55957af4d0f3 \\\\u003Cunknown>\\\\n#24 0x55957af5ce7c \\\\u003Cunknown>\\\\n#25 0x7f439ba94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x55957af5e02a <unknown>\nE       #1 0x55957ac445e0 <unknown>\nE       #2 0x55957ac3c7eb <unknown>\nE       #3 0x55957ac2ca09 <unknown>\nE       #4 0x55957ac2e744 <unknown>\nE       #5 0x55957ac2ccbd <unknown>\nE       #6 0x55957ac2c52f <unknown>\nE       #7 0x55957ac2c422 <unknown>\nE       #8 0x55957ac2a493 <unknown>\nE       #9 0x55957ac2aada <unknown>\nE       #10 0x55957ac46f41 <unknown>\nE       #11 0x55957acd88c5 <unknown>\nE       #12 0x55957acb8b22 <unknown>\nE       #13 0x55957acd7d7d <unknown>\nE       #14 0x55957acb88c3 <unknown>\nE       #15 0x55957ac866b3 <unknown>\nE       #16 0x55957ac8768e <unknown>\nE       #17 0x55957af28a2b <unknown>\nE       #18 0x55957af2c9b1 <unknown>\nE       #19 0x55957af15225 <unknown>\nE       #20 0x55957af2d532 <unknown>\nE       #21 0x55957aefa38f <unknown>\nE       #22 0x55957af4cf28 <unknown>\nE       #23 0x55957af4d0f3 <unknown>\nE       #24 0x55957af5ce7c <unknown>\nE       #25 0x7f439ba94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728694482412,
      "stop" : 1728694482412,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728694568531,
      "stop" : 1728694569172,
      "duration" : 641
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55957af5e02a <unknown>\n#1 0x55957ac445e0 <unknown>\n#2 0x55957ac3c7eb <unknown>\n#3 0x55957ac2ca09 <unknown>\n#4 0x55957ac2e744 <unknown>\n#5 0x55957ac2ccbd <unknown>\n#6 0x55957ac2c52f <unknown>\n#7 0x55957ac2c422 <unknown>\n#8 0x55957ac2a493 <unknown>\n#9 0x55957ac2aada <unknown>\n#10 0x55957ac46f41 <unknown>\n#11 0x55957acd88c5 <unknown>\n#12 0x55957acb8b22 <unknown>\n#13 0x55957acd7d7d <unknown>\n#14 0x55957acb88c3 <unknown>\n#15 0x55957ac866b3 <unknown>\n#16 0x55957ac8768e <unknown>\n#17 0x55957af28a2b <unknown>\n#18 0x55957af2c9b1 <unknown>\n#19 0x55957af15225 <unknown>\n#20 0x55957af2d532 <unknown>\n#21 0x55957aefa38f <unknown>\n#22 0x55957af4cf28 <unknown>\n#23 0x55957af4d0f3 <unknown>\n#24 0x55957af5ce7c <unknown>\n#25 0x7f439ba94ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728694568531,
        "stop" : 1728694569171,
        "duration" : 640
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55957af5e02a <unknown>\n#1 0x55957ac445e0 <unknown>\n#2 0x55957ac3c7eb <unknown>\n#3 0x55957ac2ca09 <unknown>\n#4 0x55957ac2e744 <unknown>\n#5 0x55957ac2ccbd <unknown>\n#6 0x55957ac2c52f <unknown>\n#7 0x55957ac2c422 <unknown>\n#8 0x55957ac2a493 <unknown>\n#9 0x55957ac2aada <unknown>\n#10 0x55957ac46f41 <unknown>\n#11 0x55957acd88c5 <unknown>\n#12 0x55957acb8b22 <unknown>\n#13 0x55957acd7d7d <unknown>\n#14 0x55957acb88c3 <unknown>\n#15 0x55957ac866b3 <unknown>\n#16 0x55957ac8768e <unknown>\n#17 0x55957af28a2b <unknown>\n#18 0x55957af2c9b1 <unknown>\n#19 0x55957af15225 <unknown>\n#20 0x55957af2d532 <unknown>\n#21 0x55957aefa38f <unknown>\n#22 0x55957af4cf28 <unknown>\n#23 0x55957af4d0f3 <unknown>\n#24 0x55957af5ce7c <unknown>\n#25 0x7f439ba94ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"a3ba60c53331bfecf56b11e80818f599\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728694567758,
      "stop" : 1728694568531,
      "duration" : 773
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728694569205,
      "stop" : 1728694569267,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Test Header"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "header_test"
  }, {
    "name" : "subSuite",
    "value" : "TestHeaderPage"
  }, {
    "name" : "host",
    "value" : "fv-az1245-423"
  }, {
    "name" : "thread",
    "value" : "2340-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.header_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 2,
        "skipped" : 0,
        "passed" : 76,
        "unknown" : 0,
        "total" : 78
      },
      "items" : [ {
        "uid" : "76473739c102d489",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/149//#testresult/76473739c102d489",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x56135033402a <unknown>\n#1 0x56135001a5e0 <unknown>\n#2 0x5613500127eb <unknown>\n#3 0x561350002a09 <unknown>\n#4 0x561350004744 <unknown>\n#5 0x561350002cbd <unknown>\n#6 0x56135000252f <unknown>\n#7 0x561350002422 <unknown>\n#8 0x561350000493 <unknown>\n#9 0x561350000ada <unknown>\n#10 0x56135001cf41 <unknown>\n#11 0x5613500ae8c5 <unknown>\n#12 0x56135008eb22 <unknown>\n#13 0x5613500add7d <unknown>\n#14 0x56135008e8c3 <unknown>\n#15 0x56135005c6b3 <unknown>\n#16 0x56135005d68e <unknown>\n#17 0x5613502fea2b <unknown>\n#18 0x5613503029b1 <unknown>\n#19 0x5613502eb225 <unknown>\n#20 0x561350303532 <unknown>\n#21 0x5613502d038f <unknown>\n#22 0x561350322f28 <unknown>\n#23 0x5613503230f3 <unknown>\n#24 0x561350332e7c <unknown>\n#25 0x7fd03d894ac3 <unknown>",
        "time" : {
          "start" : 1728608181211,
          "stop" : 1728608181211,
          "duration" : 0
        }
      }, {
        "uid" : "7c92a722deba50ed",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/322//#testresult/7c92a722deba50ed",
        "status" : "passed",
        "time" : {
          "start" : 1728556946741,
          "stop" : 1728556946926,
          "duration" : 185
        }
      }, {
        "uid" : "41ebb7431f661637",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/321//#testresult/41ebb7431f661637",
        "status" : "passed",
        "time" : {
          "start" : 1728553866464,
          "stop" : 1728553866648,
          "duration" : 184
        }
      }, {
        "uid" : "a214030b7e24fdb4",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/148//#testresult/a214030b7e24fdb4",
        "status" : "passed",
        "time" : {
          "start" : 1728521968153,
          "stop" : 1728521968350,
          "duration" : 197
        }
      }, {
        "uid" : "ec8f63b58397434",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/320//#testresult/ec8f63b58397434",
        "status" : "passed",
        "time" : {
          "start" : 1728470421237,
          "stop" : 1728470421451,
          "duration" : 214
        }
      }, {
        "uid" : "b87ced1a736f268b",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/319//#testresult/b87ced1a736f268b",
        "status" : "passed",
        "time" : {
          "start" : 1728467834044,
          "stop" : 1728467834234,
          "duration" : 190
        }
      }, {
        "uid" : "18d4102a61000ddf",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/147//#testresult/18d4102a61000ddf",
        "status" : "passed",
        "time" : {
          "start" : 1728435685802,
          "stop" : 1728435686038,
          "duration" : 236
        }
      }, {
        "uid" : "80162345a7e6bc3e",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/318//#testresult/80162345a7e6bc3e",
        "status" : "passed",
        "time" : {
          "start" : 1728377941154,
          "stop" : 1728377941370,
          "duration" : 216
        }
      }, {
        "uid" : "87d04d2f634b6638",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/317//#testresult/87d04d2f634b6638",
        "status" : "passed",
        "time" : {
          "start" : 1728375144342,
          "stop" : 1728375144527,
          "duration" : 185
        }
      }, {
        "uid" : "da9ec752c843658f",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/316//#testresult/da9ec752c843658f",
        "status" : "passed",
        "time" : {
          "start" : 1728375031075,
          "stop" : 1728375031287,
          "duration" : 212
        }
      }, {
        "uid" : "e1e696ff7bc8f717",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/146//#testresult/e1e696ff7bc8f717",
        "status" : "passed",
        "time" : {
          "start" : 1728349111005,
          "stop" : 1728349111217,
          "duration" : 212
        }
      }, {
        "uid" : "ed3768422a551efb",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/315//#testresult/ed3768422a551efb",
        "status" : "passed",
        "time" : {
          "start" : 1728292690083,
          "stop" : 1728292690294,
          "duration" : 211
        }
      }, {
        "uid" : "d85ebf9f7863c4cb",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/314//#testresult/d85ebf9f7863c4cb",
        "status" : "passed",
        "time" : {
          "start" : 1728289734850,
          "stop" : 1728289735115,
          "duration" : 265
        }
      }, {
        "uid" : "ca3f994de3818806",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/145//#testresult/ca3f994de3818806",
        "status" : "passed",
        "time" : {
          "start" : 1728263141569,
          "stop" : 1728263141781,
          "duration" : 212
        }
      }, {
        "uid" : "8846487522c5fdd6",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/313//#testresult/8846487522c5fdd6",
        "status" : "passed",
        "time" : {
          "start" : 1728226262784,
          "stop" : 1728226262971,
          "duration" : 187
        }
      }, {
        "uid" : "2eb2d97db7cbdcab",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/312//#testresult/2eb2d97db7cbdcab",
        "status" : "passed",
        "time" : {
          "start" : 1728221397464,
          "stop" : 1728221397677,
          "duration" : 213
        }
      }, {
        "uid" : "513017203764b4ce",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/144//#testresult/513017203764b4ce",
        "status" : "passed",
        "time" : {
          "start" : 1728176672516,
          "stop" : 1728176672726,
          "duration" : 210
        }
      }, {
        "uid" : "b18467de3e4ae1d8",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/311//#testresult/b18467de3e4ae1d8",
        "status" : "passed",
        "time" : {
          "start" : 1728117342217,
          "stop" : 1728117342423,
          "duration" : 206
        }
      }, {
        "uid" : "2e3360468b53ada8",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/310//#testresult/2e3360468b53ada8",
        "status" : "passed",
        "time" : {
          "start" : 1728108737862,
          "stop" : 1728108738072,
          "duration" : 210
        }
      }, {
        "uid" : "945b7433cbcd6460",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/143//#testresult/945b7433cbcd6460",
        "status" : "passed",
        "time" : {
          "start" : 1728089992043,
          "stop" : 1728089992249,
          "duration" : 206
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "67f606dbb1ffce64.json",
  "parameterValues" : [ ]
}