{
  "uid" : "7971951e1a02837d",
  "name" : "Verify redirection to contributors page not authorized user.",
  "fullName" : "tests.main_page_test.TestMainPage#test_mp_07_verify_redirection_to_contributors_page",
  "historyId" : "7f35157222d4ee10ae03453b93f8fb17",
  "time" : {
    "start" : 1728694616022,
    "stop" : 1728694616022,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55896389002a <unknown>\n#1 0x5589635765e0 <unknown>\n#2 0x55896356e7eb <unknown>\n#3 0x55896355ea09 <unknown>\n#4 0x558963560744 <unknown>\n#5 0x55896355ecbd <unknown>\n#6 0x55896355e52f <unknown>\n#7 0x55896355e422 <unknown>\n#8 0x55896355c493 <unknown>\n#9 0x55896355cada <unknown>\n#10 0x558963578f41 <unknown>\n#11 0x55896360a8c5 <unknown>\n#12 0x5589635eab22 <unknown>\n#13 0x558963609d7d <unknown>\n#14 0x5589635ea8c3 <unknown>\n#15 0x5589635b86b3 <unknown>\n#16 0x5589635b968e <unknown>\n#17 0x55896385aa2b <unknown>\n#18 0x55896385e9b1 <unknown>\n#19 0x558963847225 <unknown>\n#20 0x55896385f532 <unknown>\n#21 0x55896382c38f <unknown>\n#22 0x55896387ef28 <unknown>\n#23 0x55896387f0f3 <unknown>\n#24 0x55896388ee7c <unknown>\n#25 0x7f41e9c94ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"21340b3454e17cd0029e5704a1bd18c5\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f8f5b3a6fc0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x55896387f0f3 \\\\u003Cunknown>\\\\n#24 0x55896388ee7c \\\\u003Cunknown>\\\\n#25 0x7f41e9c94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x55896389002a <unknown>\nE       #1 0x5589635765e0 <unknown>\nE       #2 0x55896356e7eb <unknown>\nE       #3 0x55896355ea09 <unknown>\nE       #4 0x558963560744 <unknown>\nE       #5 0x55896355ecbd <unknown>\nE       #6 0x55896355e52f <unknown>\nE       #7 0x55896355e422 <unknown>\nE       #8 0x55896355c493 <unknown>\nE       #9 0x55896355cada <unknown>\nE       #10 0x558963578f41 <unknown>\nE       #11 0x55896360a8c5 <unknown>\nE       #12 0x5589635eab22 <unknown>\nE       #13 0x558963609d7d <unknown>\nE       #14 0x5589635ea8c3 <unknown>\nE       #15 0x5589635b86b3 <unknown>\nE       #16 0x5589635b968e <unknown>\nE       #17 0x55896385aa2b <unknown>\nE       #18 0x55896385e9b1 <unknown>\nE       #19 0x558963847225 <unknown>\nE       #20 0x55896385f532 <unknown>\nE       #21 0x55896382c38f <unknown>\nE       #22 0x55896387ef28 <unknown>\nE       #23 0x55896387f0f3 <unknown>\nE       #24 0x55896388ee7c <unknown>\nE       #25 0x7f41e9c94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728694482412,
      "stop" : 1728694482412,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728694616022,
      "stop" : 1728694616796,
      "duration" : 774
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728694616796,
      "stop" : 1728694617429,
      "duration" : 633
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55896389002a <unknown>\n#1 0x5589635765e0 <unknown>\n#2 0x55896356e7eb <unknown>\n#3 0x55896355ea09 <unknown>\n#4 0x558963560744 <unknown>\n#5 0x55896355ecbd <unknown>\n#6 0x55896355e52f <unknown>\n#7 0x55896355e422 <unknown>\n#8 0x55896355c493 <unknown>\n#9 0x55896355cada <unknown>\n#10 0x558963578f41 <unknown>\n#11 0x55896360a8c5 <unknown>\n#12 0x5589635eab22 <unknown>\n#13 0x558963609d7d <unknown>\n#14 0x5589635ea8c3 <unknown>\n#15 0x5589635b86b3 <unknown>\n#16 0x5589635b968e <unknown>\n#17 0x55896385aa2b <unknown>\n#18 0x55896385e9b1 <unknown>\n#19 0x558963847225 <unknown>\n#20 0x55896385f532 <unknown>\n#21 0x55896382c38f <unknown>\n#22 0x55896387ef28 <unknown>\n#23 0x55896387f0f3 <unknown>\n#24 0x55896388ee7c <unknown>\n#25 0x7f41e9c94ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728694616796,
        "stop" : 1728694617429,
        "duration" : 633
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55896389002a <unknown>\n#1 0x5589635765e0 <unknown>\n#2 0x55896356e7eb <unknown>\n#3 0x55896355ea09 <unknown>\n#4 0x558963560744 <unknown>\n#5 0x55896355ecbd <unknown>\n#6 0x55896355e52f <unknown>\n#7 0x55896355e422 <unknown>\n#8 0x55896355c493 <unknown>\n#9 0x55896355cada <unknown>\n#10 0x558963578f41 <unknown>\n#11 0x55896360a8c5 <unknown>\n#12 0x5589635eab22 <unknown>\n#13 0x558963609d7d <unknown>\n#14 0x5589635ea8c3 <unknown>\n#15 0x5589635b86b3 <unknown>\n#16 0x5589635b968e <unknown>\n#17 0x55896385aa2b <unknown>\n#18 0x55896385e9b1 <unknown>\n#19 0x558963847225 <unknown>\n#20 0x55896385f532 <unknown>\n#21 0x55896382c38f <unknown>\n#22 0x55896387ef28 <unknown>\n#23 0x55896387f0f3 <unknown>\n#24 0x55896388ee7c <unknown>\n#25 0x7f41e9c94ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"21340b3454e17cd0029e5704a1bd18c5\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728694617462,
      "stop" : 1728694617524,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Main Page."
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "main_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestMainPage"
  }, {
    "name" : "host",
    "value" : "fv-az1245-423"
  }, {
    "name" : "thread",
    "value" : "2340-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.main_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 10,
        "skipped" : 0,
        "passed" : 488,
        "unknown" : 0,
        "total" : 498
      },
      "items" : [ {
        "uid" : "3311d2ad18e50459",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/149//#testresult/3311d2ad18e50459",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55cc17fd502a <unknown>\n#1 0x55cc17cbb5e0 <unknown>\n#2 0x55cc17cb37eb <unknown>\n#3 0x55cc17ca3a09 <unknown>\n#4 0x55cc17ca5744 <unknown>\n#5 0x55cc17ca3cbd <unknown>\n#6 0x55cc17ca352f <unknown>\n#7 0x55cc17ca3422 <unknown>\n#8 0x55cc17ca1493 <unknown>\n#9 0x55cc17ca1ada <unknown>\n#10 0x55cc17cbdf41 <unknown>\n#11 0x55cc17d4f8c5 <unknown>\n#12 0x55cc17d2fb22 <unknown>\n#13 0x55cc17d4ed7d <unknown>\n#14 0x55cc17d2f8c3 <unknown>\n#15 0x55cc17cfd6b3 <unknown>\n#16 0x55cc17cfe68e <unknown>\n#17 0x55cc17f9fa2b <unknown>\n#18 0x55cc17fa39b1 <unknown>\n#19 0x55cc17f8c225 <unknown>\n#20 0x55cc17fa4532 <unknown>\n#21 0x55cc17f7138f <unknown>\n#22 0x55cc17fc3f28 <unknown>\n#23 0x55cc17fc40f3 <unknown>\n#24 0x55cc17fd3e7c <unknown>\n#25 0x7f041e894ac3 <unknown>",
        "time" : {
          "start" : 1728608224241,
          "stop" : 1728608224241,
          "duration" : 0
        }
      }, {
        "uid" : "d612573c5c18397b",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/322//#testresult/d612573c5c18397b",
        "status" : "passed",
        "time" : {
          "start" : 1728557198871,
          "stop" : 1728557199545,
          "duration" : 674
        }
      }, {
        "uid" : "112891cc288b94f0",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/321//#testresult/112891cc288b94f0",
        "status" : "passed",
        "time" : {
          "start" : 1728554086685,
          "stop" : 1728554087349,
          "duration" : 664
        }
      }, {
        "uid" : "cdceed6999fe96f",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/148//#testresult/cdceed6999fe96f",
        "status" : "passed",
        "time" : {
          "start" : 1728522069151,
          "stop" : 1728522069807,
          "duration" : 656
        }
      }, {
        "uid" : "d9b47d1397ee8fe1",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/320//#testresult/d9b47d1397ee8fe1",
        "status" : "passed",
        "time" : {
          "start" : 1728470497968,
          "stop" : 1728470498650,
          "duration" : 682
        }
      }, {
        "uid" : "cb4bf549f1b5a1a7",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/319//#testresult/cb4bf549f1b5a1a7",
        "status" : "passed",
        "time" : {
          "start" : 1728467915822,
          "stop" : 1728467916483,
          "duration" : 661
        }
      }, {
        "uid" : "17aed36c58c06f99",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/147//#testresult/17aed36c58c06f99",
        "status" : "passed",
        "time" : {
          "start" : 1728435785864,
          "stop" : 1728435786577,
          "duration" : 713
        }
      }, {
        "uid" : "899ff6fd554c43b6",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/318//#testresult/899ff6fd554c43b6",
        "status" : "passed",
        "time" : {
          "start" : 1728378015288,
          "stop" : 1728378015944,
          "duration" : 656
        }
      }, {
        "uid" : "e75d9a5478f6742f",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/317//#testresult/e75d9a5478f6742f",
        "status" : "passed",
        "time" : {
          "start" : 1728375221940,
          "stop" : 1728375222607,
          "duration" : 667
        }
      }, {
        "uid" : "366684d8be76846f",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/316//#testresult/366684d8be76846f",
        "status" : "passed",
        "time" : {
          "start" : 1728375106697,
          "stop" : 1728375107370,
          "duration" : 673
        }
      }, {
        "uid" : "1b852531f9d478f3",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/146//#testresult/1b852531f9d478f3",
        "status" : "passed",
        "time" : {
          "start" : 1728349190191,
          "stop" : 1728349190861,
          "duration" : 670
        }
      }, {
        "uid" : "f64456420489e7cd",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/315//#testresult/f64456420489e7cd",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/contributors",
        "time" : {
          "start" : 1728292844182,
          "stop" : 1728292884621,
          "duration" : 40439
        }
      }, {
        "uid" : "997e7a9fdd2d3fdb",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/314//#testresult/997e7a9fdd2d3fdb",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/contributors",
        "time" : {
          "start" : 1728289891659,
          "stop" : 1728289932110,
          "duration" : 40451
        }
      }, {
        "uid" : "355c9de717e8894e",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/145//#testresult/355c9de717e8894e",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/contributors",
        "time" : {
          "start" : 1728263296498,
          "stop" : 1728263336911,
          "duration" : 40413
        }
      }, {
        "uid" : "a2890aa95b42fb2f",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/313//#testresult/a2890aa95b42fb2f",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/contributors",
        "time" : {
          "start" : 1728226438636,
          "stop" : 1728226479050,
          "duration" : 40414
        }
      }, {
        "uid" : "51451a8b70ae5105",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/312//#testresult/51451a8b70ae5105",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/contributors",
        "time" : {
          "start" : 1728221556218,
          "stop" : 1728221596651,
          "duration" : 40433
        }
      }, {
        "uid" : "7f4ae393c9a8df3",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/144//#testresult/7f4ae393c9a8df3",
        "status" : "passed",
        "time" : {
          "start" : 1728176922237,
          "stop" : 1728176922889,
          "duration" : 652
        }
      }, {
        "uid" : "b468524c38c58dd7",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/311//#testresult/b468524c38c58dd7",
        "status" : "passed",
        "time" : {
          "start" : 1728117558324,
          "stop" : 1728117558971,
          "duration" : 647
        }
      }, {
        "uid" : "f4e64ee9a8944a94",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/310//#testresult/f4e64ee9a8944a94",
        "status" : "passed",
        "time" : {
          "start" : 1728108941585,
          "stop" : 1728108942234,
          "duration" : 649
        }
      }, {
        "uid" : "cf2dc80f961021ca",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/143//#testresult/cf2dc80f961021ca",
        "status" : "passed",
        "time" : {
          "start" : 1728090199333,
          "stop" : 1728090199988,
          "duration" : 655
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "7971951e1a02837d.json",
  "parameterValues" : [ ]
}