{
  "uid" : "9a63cef25c664f67",
  "name" : "Verify text in links in the section 2",
  "fullName" : "tests.contacts_page_test.TestContactsPageText#test_cp_02_04_verify_text_in_links",
  "historyId" : "4515387d136afc8202bec73eb2af416d",
  "time" : {
    "start" : 1728694525490,
    "stop" : 1728694525490,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55840376d02a <unknown>\n#1 0x5584034535e0 <unknown>\n#2 0x55840344b7eb <unknown>\n#3 0x55840343ba09 <unknown>\n#4 0x55840343d744 <unknown>\n#5 0x55840343bcbd <unknown>\n#6 0x55840343b52f <unknown>\n#7 0x55840343b422 <unknown>\n#8 0x558403439493 <unknown>\n#9 0x558403439ada <unknown>\n#10 0x558403455f41 <unknown>\n#11 0x5584034e78c5 <unknown>\n#12 0x5584034c7b22 <unknown>\n#13 0x5584034e6d7d <unknown>\n#14 0x5584034c78c3 <unknown>\n#15 0x5584034956b3 <unknown>\n#16 0x55840349668e <unknown>\n#17 0x558403737a2b <unknown>\n#18 0x55840373b9b1 <unknown>\n#19 0x558403724225 <unknown>\n#20 0x55840373c532 <unknown>\n#21 0x55840370938f <unknown>\n#22 0x55840375bf28 <unknown>\n#23 0x55840375c0f3 <unknown>\n#24 0x55840376be7c <unknown>\n#25 0x7fe63d694ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"3d1db341a4a840eba841de925e2f711b\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f8f5b5e22a0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x55840375c0f3 \\\\u003Cunknown>\\\\n#24 0x55840376be7c \\\\u003Cunknown>\\\\n#25 0x7fe63d694ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x55840376d02a <unknown>\nE       #1 0x5584034535e0 <unknown>\nE       #2 0x55840344b7eb <unknown>\nE       #3 0x55840343ba09 <unknown>\nE       #4 0x55840343d744 <unknown>\nE       #5 0x55840343bcbd <unknown>\nE       #6 0x55840343b52f <unknown>\nE       #7 0x55840343b422 <unknown>\nE       #8 0x558403439493 <unknown>\nE       #9 0x558403439ada <unknown>\nE       #10 0x558403455f41 <unknown>\nE       #11 0x5584034e78c5 <unknown>\nE       #12 0x5584034c7b22 <unknown>\nE       #13 0x5584034e6d7d <unknown>\nE       #14 0x5584034c78c3 <unknown>\nE       #15 0x5584034956b3 <unknown>\nE       #16 0x55840349668e <unknown>\nE       #17 0x558403737a2b <unknown>\nE       #18 0x55840373b9b1 <unknown>\nE       #19 0x558403724225 <unknown>\nE       #20 0x55840373c532 <unknown>\nE       #21 0x55840370938f <unknown>\nE       #22 0x55840375bf28 <unknown>\nE       #23 0x55840375c0f3 <unknown>\nE       #24 0x55840376be7c <unknown>\nE       #25 0x7fe63d694ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728694482412,
      "stop" : 1728694482412,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728694526273,
      "stop" : 1728694526909,
      "duration" : 636
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55840376d02a <unknown>\n#1 0x5584034535e0 <unknown>\n#2 0x55840344b7eb <unknown>\n#3 0x55840343ba09 <unknown>\n#4 0x55840343d744 <unknown>\n#5 0x55840343bcbd <unknown>\n#6 0x55840343b52f <unknown>\n#7 0x55840343b422 <unknown>\n#8 0x558403439493 <unknown>\n#9 0x558403439ada <unknown>\n#10 0x558403455f41 <unknown>\n#11 0x5584034e78c5 <unknown>\n#12 0x5584034c7b22 <unknown>\n#13 0x5584034e6d7d <unknown>\n#14 0x5584034c78c3 <unknown>\n#15 0x5584034956b3 <unknown>\n#16 0x55840349668e <unknown>\n#17 0x558403737a2b <unknown>\n#18 0x55840373b9b1 <unknown>\n#19 0x558403724225 <unknown>\n#20 0x55840373c532 <unknown>\n#21 0x55840370938f <unknown>\n#22 0x55840375bf28 <unknown>\n#23 0x55840375c0f3 <unknown>\n#24 0x55840376be7c <unknown>\n#25 0x7fe63d694ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728694526273,
        "stop" : 1728694526909,
        "duration" : 636
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55840376d02a <unknown>\n#1 0x5584034535e0 <unknown>\n#2 0x55840344b7eb <unknown>\n#3 0x55840343ba09 <unknown>\n#4 0x55840343d744 <unknown>\n#5 0x55840343bcbd <unknown>\n#6 0x55840343b52f <unknown>\n#7 0x55840343b422 <unknown>\n#8 0x558403439493 <unknown>\n#9 0x558403439ada <unknown>\n#10 0x558403455f41 <unknown>\n#11 0x5584034e78c5 <unknown>\n#12 0x5584034c7b22 <unknown>\n#13 0x5584034e6d7d <unknown>\n#14 0x5584034c78c3 <unknown>\n#15 0x5584034956b3 <unknown>\n#16 0x55840349668e <unknown>\n#17 0x558403737a2b <unknown>\n#18 0x55840373b9b1 <unknown>\n#19 0x558403724225 <unknown>\n#20 0x55840373c532 <unknown>\n#21 0x55840370938f <unknown>\n#22 0x55840375bf28 <unknown>\n#23 0x55840375c0f3 <unknown>\n#24 0x55840376be7c <unknown>\n#25 0x7fe63d694ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"3d1db341a4a840eba841de925e2f711b\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728694525490,
      "stop" : 1728694526273,
      "duration" : 783
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728694526941,
      "stop" : 1728694527002,
      "duration" : 61
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "The Contacts Page"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "contacts_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestContactsPage"
  }, {
    "name" : "host",
    "value" : "fv-az1245-423"
  }, {
    "name" : "thread",
    "value" : "2340-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.contacts_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 6,
        "skipped" : 0,
        "passed" : 492,
        "unknown" : 0,
        "total" : 498
      },
      "items" : [ {
        "uid" : "bccbf810e6669e09",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/149//#testresult/bccbf810e6669e09",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55e52dea602a <unknown>\n#1 0x55e52db8c5e0 <unknown>\n#2 0x55e52db847eb <unknown>\n#3 0x55e52db74a09 <unknown>\n#4 0x55e52db76744 <unknown>\n#5 0x55e52db74cbd <unknown>\n#6 0x55e52db7452f <unknown>\n#7 0x55e52db74422 <unknown>\n#8 0x55e52db72493 <unknown>\n#9 0x55e52db72ada <unknown>\n#10 0x55e52db8ef41 <unknown>\n#11 0x55e52dc208c5 <unknown>\n#12 0x55e52dc00b22 <unknown>\n#13 0x55e52dc1fd7d <unknown>\n#14 0x55e52dc008c3 <unknown>\n#15 0x55e52dbce6b3 <unknown>\n#16 0x55e52dbcf68e <unknown>\n#17 0x55e52de70a2b <unknown>\n#18 0x55e52de749b1 <unknown>\n#19 0x55e52de5d225 <unknown>\n#20 0x55e52de75532 <unknown>\n#21 0x55e52de4238f <unknown>\n#22 0x55e52de94f28 <unknown>\n#23 0x55e52de950f3 <unknown>\n#24 0x55e52dea4e7c <unknown>\n#25 0x7fa050c94ac3 <unknown>",
        "time" : {
          "start" : 1728608143579,
          "stop" : 1728608143579,
          "duration" : 0
        }
      }, {
        "uid" : "3abfeba83d9f5472",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/322//#testresult/3abfeba83d9f5472",
        "status" : "passed",
        "time" : {
          "start" : 1728556765691,
          "stop" : 1728556765721,
          "duration" : 30
        }
      }, {
        "uid" : "d587fcd6c9cfdc52",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/321//#testresult/d587fcd6c9cfdc52",
        "status" : "passed",
        "time" : {
          "start" : 1728553706077,
          "stop" : 1728553706107,
          "duration" : 30
        }
      }, {
        "uid" : "e83e715de9812b41",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/148//#testresult/e83e715de9812b41",
        "status" : "passed",
        "time" : {
          "start" : 1728521790573,
          "stop" : 1728521790602,
          "duration" : 29
        }
      }, {
        "uid" : "cb64cd95189f8dc5",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/320//#testresult/cb64cd95189f8dc5",
        "status" : "passed",
        "time" : {
          "start" : 1728470281970,
          "stop" : 1728470282001,
          "duration" : 31
        }
      }, {
        "uid" : "477dc980e128a2a3",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/319//#testresult/477dc980e128a2a3",
        "status" : "passed",
        "time" : {
          "start" : 1728467686333,
          "stop" : 1728467686364,
          "duration" : 31
        }
      }, {
        "uid" : "1a724e2741375e7c",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/147//#testresult/1a724e2741375e7c",
        "status" : "passed",
        "time" : {
          "start" : 1728435387546,
          "stop" : 1728435387579,
          "duration" : 33
        }
      }, {
        "uid" : "b0dbdf685d48fd69",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/318//#testresult/b0dbdf685d48fd69",
        "status" : "passed",
        "time" : {
          "start" : 1728377807297,
          "stop" : 1728377807328,
          "duration" : 31
        }
      }, {
        "uid" : "d8d9138983033299",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/317//#testresult/d8d9138983033299",
        "status" : "passed",
        "time" : {
          "start" : 1728375007791,
          "stop" : 1728375007820,
          "duration" : 29
        }
      }, {
        "uid" : "689f5b29393eb712",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/316//#testresult/689f5b29393eb712",
        "status" : "passed",
        "time" : {
          "start" : 1728374897435,
          "stop" : 1728374897463,
          "duration" : 28
        }
      }, {
        "uid" : "1026415cee483365",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/146//#testresult/1026415cee483365",
        "status" : "passed",
        "time" : {
          "start" : 1728348985899,
          "stop" : 1728348985930,
          "duration" : 31
        }
      }, {
        "uid" : "cc0461dbb2e9f705",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/315//#testresult/cc0461dbb2e9f705",
        "status" : "passed",
        "time" : {
          "start" : 1728292488124,
          "stop" : 1728292488154,
          "duration" : 30
        }
      }, {
        "uid" : "6e78aff96a092d1f",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/314//#testresult/6e78aff96a092d1f",
        "status" : "passed",
        "time" : {
          "start" : 1728289528484,
          "stop" : 1728289528513,
          "duration" : 29
        }
      }, {
        "uid" : "5ce04c78d5caa042",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/145//#testresult/5ce04c78d5caa042",
        "status" : "passed",
        "time" : {
          "start" : 1728262707417,
          "stop" : 1728262707446,
          "duration" : 29
        }
      }, {
        "uid" : "dc6b03eb647f2659",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/313//#testresult/dc6b03eb647f2659",
        "status" : "passed",
        "time" : {
          "start" : 1728225780663,
          "stop" : 1728225780692,
          "duration" : 29
        }
      }, {
        "uid" : "9c0d532de9142e58",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/312//#testresult/9c0d532de9142e58",
        "status" : "passed",
        "time" : {
          "start" : 1728220948418,
          "stop" : 1728220948448,
          "duration" : 30
        }
      }, {
        "uid" : "9aa50c3b3336d161",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/144//#testresult/9aa50c3b3336d161",
        "status" : "passed",
        "time" : {
          "start" : 1728176460300,
          "stop" : 1728176460330,
          "duration" : 30
        }
      }, {
        "uid" : "1f0c578186bf7055",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/311//#testresult/1f0c578186bf7055",
        "status" : "passed",
        "time" : {
          "start" : 1728117132446,
          "stop" : 1728117132477,
          "duration" : 31
        }
      }, {
        "uid" : "6bdfca00776bb4b7",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/310//#testresult/6bdfca00776bb4b7",
        "status" : "passed",
        "time" : {
          "start" : 1728108545899,
          "stop" : 1728108545936,
          "duration" : 37
        }
      }, {
        "uid" : "c3e0c1bfeaef23c7",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/143//#testresult/c3e0c1bfeaef23c7",
        "status" : "passed",
        "time" : {
          "start" : 1728089803932,
          "stop" : 1728089803961,
          "duration" : 29
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "9a63cef25c664f67.json",
  "parameterValues" : [ ]
}