{
  "uid" : "114e2367aea349f6",
  "name" : "Verify presence, visibility, clickability, href, status code \n                         of the 'Login' link in the section 1",
  "fullName" : "tests.start_unauthorized_page_test.TestStartUnauthorizedPageLinks#test_su_03_01_verify_login_link",
  "historyId" : "c97456d3938f7be35b662f54dc730fcd",
  "time" : {
    "start" : 1728781342682,
    "stop" : 1728781342682,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x564d73d0b02a <unknown>\n#1 0x564d739f15e0 <unknown>\n#2 0x564d739e97eb <unknown>\n#3 0x564d739d9a09 <unknown>\n#4 0x564d739db744 <unknown>\n#5 0x564d739d9cbd <unknown>\n#6 0x564d739d952f <unknown>\n#7 0x564d739d9422 <unknown>\n#8 0x564d739d7493 <unknown>\n#9 0x564d739d7ada <unknown>\n#10 0x564d739f3f41 <unknown>\n#11 0x564d73a858c5 <unknown>\n#12 0x564d73a65b22 <unknown>\n#13 0x564d73a84d7d <unknown>\n#14 0x564d73a658c3 <unknown>\n#15 0x564d73a336b3 <unknown>\n#16 0x564d73a3468e <unknown>\n#17 0x564d73cd5a2b <unknown>\n#18 0x564d73cd99b1 <unknown>\n#19 0x564d73cc2225 <unknown>\n#20 0x564d73cda532 <unknown>\n#21 0x564d73ca738f <unknown>\n#22 0x564d73cf9f28 <unknown>\n#23 0x564d73cfa0f3 <unknown>\n#24 0x564d73d09e7c <unknown>\n#25 0x7fdcc5094ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a873503740dd298a9ef6f30d88ea42a8\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fe0c0e18380>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x564d73cfa0f3 \\\\u003Cunknown>\\\\n#24 0x564d73d09e7c \\\\u003Cunknown>\\\\n#25 0x7fdcc5094ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x564d73d0b02a <unknown>\nE       #1 0x564d739f15e0 <unknown>\nE       #2 0x564d739e97eb <unknown>\nE       #3 0x564d739d9a09 <unknown>\nE       #4 0x564d739db744 <unknown>\nE       #5 0x564d739d9cbd <unknown>\nE       #6 0x564d739d952f <unknown>\nE       #7 0x564d739d9422 <unknown>\nE       #8 0x564d739d7493 <unknown>\nE       #9 0x564d739d7ada <unknown>\nE       #10 0x564d739f3f41 <unknown>\nE       #11 0x564d73a858c5 <unknown>\nE       #12 0x564d73a65b22 <unknown>\nE       #13 0x564d73a84d7d <unknown>\nE       #14 0x564d73a658c3 <unknown>\nE       #15 0x564d73a336b3 <unknown>\nE       #16 0x564d73a3468e <unknown>\nE       #17 0x564d73cd5a2b <unknown>\nE       #18 0x564d73cd99b1 <unknown>\nE       #19 0x564d73cc2225 <unknown>\nE       #20 0x564d73cda532 <unknown>\nE       #21 0x564d73ca738f <unknown>\nE       #22 0x564d73cf9f28 <unknown>\nE       #23 0x564d73cfa0f3 <unknown>\nE       #24 0x564d73d09e7c <unknown>\nE       #25 0x7fdcc5094ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728781182641,
      "stop" : 1728781182641,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728781342682,
      "stop" : 1728781343460,
      "duration" : 778
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728781343460,
      "stop" : 1728781344057,
      "duration" : 597
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x564d73d0b02a <unknown>\n#1 0x564d739f15e0 <unknown>\n#2 0x564d739e97eb <unknown>\n#3 0x564d739d9a09 <unknown>\n#4 0x564d739db744 <unknown>\n#5 0x564d739d9cbd <unknown>\n#6 0x564d739d952f <unknown>\n#7 0x564d739d9422 <unknown>\n#8 0x564d739d7493 <unknown>\n#9 0x564d739d7ada <unknown>\n#10 0x564d739f3f41 <unknown>\n#11 0x564d73a858c5 <unknown>\n#12 0x564d73a65b22 <unknown>\n#13 0x564d73a84d7d <unknown>\n#14 0x564d73a658c3 <unknown>\n#15 0x564d73a336b3 <unknown>\n#16 0x564d73a3468e <unknown>\n#17 0x564d73cd5a2b <unknown>\n#18 0x564d73cd99b1 <unknown>\n#19 0x564d73cc2225 <unknown>\n#20 0x564d73cda532 <unknown>\n#21 0x564d73ca738f <unknown>\n#22 0x564d73cf9f28 <unknown>\n#23 0x564d73cfa0f3 <unknown>\n#24 0x564d73d09e7c <unknown>\n#25 0x7fdcc5094ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728781343460,
        "stop" : 1728781344057,
        "duration" : 597
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x564d73d0b02a <unknown>\n#1 0x564d739f15e0 <unknown>\n#2 0x564d739e97eb <unknown>\n#3 0x564d739d9a09 <unknown>\n#4 0x564d739db744 <unknown>\n#5 0x564d739d9cbd <unknown>\n#6 0x564d739d952f <unknown>\n#7 0x564d739d9422 <unknown>\n#8 0x564d739d7493 <unknown>\n#9 0x564d739d7ada <unknown>\n#10 0x564d739f3f41 <unknown>\n#11 0x564d73a858c5 <unknown>\n#12 0x564d73a65b22 <unknown>\n#13 0x564d73a84d7d <unknown>\n#14 0x564d73a658c3 <unknown>\n#15 0x564d73a336b3 <unknown>\n#16 0x564d73a3468e <unknown>\n#17 0x564d73cd5a2b <unknown>\n#18 0x564d73cd99b1 <unknown>\n#19 0x564d73cc2225 <unknown>\n#20 0x564d73cda532 <unknown>\n#21 0x564d73ca738f <unknown>\n#22 0x564d73cf9f28 <unknown>\n#23 0x564d73cfa0f3 <unknown>\n#24 0x564d73d09e7c <unknown>\n#25 0x7fdcc5094ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"a873503740dd298a9ef6f30d88ea42a8\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728781344090,
      "stop" : 1728781344152,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "The Start Unauthorized Page"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "start_unauthorized_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestStartUnauthorizedPage"
  }, {
    "name" : "host",
    "value" : "fv-az585-604"
  }, {
    "name" : "thread",
    "value" : "2289-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.start_unauthorized_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 6,
        "skipped" : 0,
        "passed" : 392,
        "unknown" : 0,
        "total" : 398
      },
      "items" : [ {
        "uid" : "76c5b7a9d7a8e83f",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/150//#testresult/76c5b7a9d7a8e83f",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55f71302202a <unknown>\n#1 0x55f712d085e0 <unknown>\n#2 0x55f712d007eb <unknown>\n#3 0x55f712cf0a09 <unknown>\n#4 0x55f712cf2744 <unknown>\n#5 0x55f712cf0cbd <unknown>\n#6 0x55f712cf052f <unknown>\n#7 0x55f712cf0422 <unknown>\n#8 0x55f712cee493 <unknown>\n#9 0x55f712ceeada <unknown>\n#10 0x55f712d0af41 <unknown>\n#11 0x55f712d9c8c5 <unknown>\n#12 0x55f712d7cb22 <unknown>\n#13 0x55f712d9bd7d <unknown>\n#14 0x55f712d7c8c3 <unknown>\n#15 0x55f712d4a6b3 <unknown>\n#16 0x55f712d4b68e <unknown>\n#17 0x55f712feca2b <unknown>\n#18 0x55f712ff09b1 <unknown>\n#19 0x55f712fd9225 <unknown>\n#20 0x55f712ff1532 <unknown>\n#21 0x55f712fbe38f <unknown>\n#22 0x55f713010f28 <unknown>\n#23 0x55f7130110f3 <unknown>\n#24 0x55f713020e7c <unknown>\n#25 0x7f6175a94ac3 <unknown>",
        "time" : {
          "start" : 1728694668780,
          "stop" : 1728694668780,
          "duration" : 0
        }
      }, {
        "uid" : "2525acf29aa3b575",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/149//#testresult/2525acf29aa3b575",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x556702e8c02a <unknown>\n#1 0x556702b725e0 <unknown>\n#2 0x556702b6a7eb <unknown>\n#3 0x556702b5aa09 <unknown>\n#4 0x556702b5c744 <unknown>\n#5 0x556702b5acbd <unknown>\n#6 0x556702b5a52f <unknown>\n#7 0x556702b5a422 <unknown>\n#8 0x556702b58493 <unknown>\n#9 0x556702b58ada <unknown>\n#10 0x556702b74f41 <unknown>\n#11 0x556702c068c5 <unknown>\n#12 0x556702be6b22 <unknown>\n#13 0x556702c05d7d <unknown>\n#14 0x556702be68c3 <unknown>\n#15 0x556702bb46b3 <unknown>\n#16 0x556702bb568e <unknown>\n#17 0x556702e56a2b <unknown>\n#18 0x556702e5a9b1 <unknown>\n#19 0x556702e43225 <unknown>\n#20 0x556702e5b532 <unknown>\n#21 0x556702e2838f <unknown>\n#22 0x556702e7af28 <unknown>\n#23 0x556702e7b0f3 <unknown>\n#24 0x556702e8ae7c <unknown>\n#25 0x7f9991e94ac3 <unknown>",
        "time" : {
          "start" : 1728608271390,
          "stop" : 1728608271390,
          "duration" : 0
        }
      }, {
        "uid" : "840ec63a2432b9a",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/322//#testresult/840ec63a2432b9a",
        "status" : "passed",
        "time" : {
          "start" : 1728557435463,
          "stop" : 1728557436084,
          "duration" : 621
        }
      }, {
        "uid" : "463ca2643c662423",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/321//#testresult/463ca2643c662423",
        "status" : "passed",
        "time" : {
          "start" : 1728554299870,
          "stop" : 1728554300523,
          "duration" : 653
        }
      }, {
        "uid" : "8ae6cc45e902c46e",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/148//#testresult/8ae6cc45e902c46e",
        "status" : "passed",
        "time" : {
          "start" : 1728522311123,
          "stop" : 1728522312001,
          "duration" : 878
        }
      }, {
        "uid" : "14712022e4ae372",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/320//#testresult/14712022e4ae372",
        "status" : "passed",
        "time" : {
          "start" : 1728470693725,
          "stop" : 1728470694217,
          "duration" : 492
        }
      }, {
        "uid" : "a9492289341e0cda",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/319//#testresult/a9492289341e0cda",
        "status" : "passed",
        "time" : {
          "start" : 1728468124316,
          "stop" : 1728468124842,
          "duration" : 526
        }
      }, {
        "uid" : "bb2d596cad578c97",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/147//#testresult/bb2d596cad578c97",
        "status" : "passed",
        "time" : {
          "start" : 1728435937899,
          "stop" : 1728435938578,
          "duration" : 679
        }
      }, {
        "uid" : "3d36777d419436b0",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/318//#testresult/3d36777d419436b0",
        "status" : "passed",
        "time" : {
          "start" : 1728378136874,
          "stop" : 1728378137445,
          "duration" : 571
        }
      }, {
        "uid" : "f1cd22ca238400ca",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/317//#testresult/f1cd22ca238400ca",
        "status" : "passed",
        "time" : {
          "start" : 1728375346886,
          "stop" : 1728375347479,
          "duration" : 593
        }
      }, {
        "uid" : "4305cfe86b29178e",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/316//#testresult/4305cfe86b29178e",
        "status" : "passed",
        "time" : {
          "start" : 1728375228021,
          "stop" : 1728375228632,
          "duration" : 611
        }
      }, {
        "uid" : "d00af73d781e0ea4",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/146//#testresult/d00af73d781e0ea4",
        "status" : "passed",
        "time" : {
          "start" : 1728349316199,
          "stop" : 1728349316785,
          "duration" : 586
        }
      }, {
        "uid" : "6493605527b2dd7",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/315//#testresult/6493605527b2dd7",
        "status" : "passed",
        "time" : {
          "start" : 1728293065927,
          "stop" : 1728293066567,
          "duration" : 640
        }
      }, {
        "uid" : "fb4ceee140ffd356",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/314//#testresult/fb4ceee140ffd356",
        "status" : "passed",
        "time" : {
          "start" : 1728290116968,
          "stop" : 1728290117587,
          "duration" : 619
        }
      }, {
        "uid" : "6f24ff8e8038d6f6",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/145//#testresult/6f24ff8e8038d6f6",
        "status" : "passed",
        "time" : {
          "start" : 1728263763223,
          "stop" : 1728263763843,
          "duration" : 620
        }
      }, {
        "uid" : "ebde054911b13e26",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/313//#testresult/ebde054911b13e26",
        "status" : "passed",
        "time" : {
          "start" : 1728226946912,
          "stop" : 1728226947777,
          "duration" : 865
        }
      }, {
        "uid" : "64b1f3b3d121d777",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/312//#testresult/64b1f3b3d121d777",
        "status" : "passed",
        "time" : {
          "start" : 1728222032888,
          "stop" : 1728222033592,
          "duration" : 704
        }
      }, {
        "uid" : "eb66e46b86353961",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/144//#testresult/eb66e46b86353961",
        "status" : "passed",
        "time" : {
          "start" : 1728177130120,
          "stop" : 1728177130814,
          "duration" : 694
        }
      }, {
        "uid" : "4e9b7ea502da7fc8",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/311//#testresult/4e9b7ea502da7fc8",
        "status" : "passed",
        "time" : {
          "start" : 1728117760683,
          "stop" : 1728117761214,
          "duration" : 531
        }
      }, {
        "uid" : "39ce99f94822c906",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/310//#testresult/39ce99f94822c906",
        "status" : "passed",
        "time" : {
          "start" : 1728109136880,
          "stop" : 1728109137475,
          "duration" : 595
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "114e2367aea349f6.json",
  "parameterValues" : [ ]
}