{
  "uid" : "1b8ccb634f1d8804",
  "name" : "test_registration_negative[new email and empty email-Auto Test-1981--password-password-error_message5]",
  "fullName" : "tests.registration_page_test.TestRegistrationPage#test_registration_negative",
  "historyId" : "68bdd8444764e24f0a4544c9ae38f663",
  "time" : {
    "start" : 1728781307368,
    "stop" : 1728781307368,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55bdee0ec02a <unknown>\n#1 0x55bdeddd25e0 <unknown>\n#2 0x55bdeddca7eb <unknown>\n#3 0x55bdeddbaa09 <unknown>\n#4 0x55bdeddbc744 <unknown>\n#5 0x55bdeddbacbd <unknown>\n#6 0x55bdeddba52f <unknown>\n#7 0x55bdeddba422 <unknown>\n#8 0x55bdeddb8493 <unknown>\n#9 0x55bdeddb8ada <unknown>\n#10 0x55bdeddd4f41 <unknown>\n#11 0x55bdede668c5 <unknown>\n#12 0x55bdede46b22 <unknown>\n#13 0x55bdede65d7d <unknown>\n#14 0x55bdede468c3 <unknown>\n#15 0x55bdede146b3 <unknown>\n#16 0x55bdede1568e <unknown>\n#17 0x55bdee0b6a2b <unknown>\n#18 0x55bdee0ba9b1 <unknown>\n#19 0x55bdee0a3225 <unknown>\n#20 0x55bdee0bb532 <unknown>\n#21 0x55bdee08838f <unknown>\n#22 0x55bdee0daf28 <unknown>\n#23 0x55bdee0db0f3 <unknown>\n#24 0x55bdee0eae7c <unknown>\n#25 0x7fcb44694ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"c6fcd102d6deddb647beb2e30180a9dd\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fe0c0fc86e0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x55bdee0db0f3 \\\\u003Cunknown>\\\\n#24 0x55bdee0eae7c \\\\u003Cunknown>\\\\n#25 0x7fcb44694ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x55bdee0ec02a <unknown>\nE       #1 0x55bdeddd25e0 <unknown>\nE       #2 0x55bdeddca7eb <unknown>\nE       #3 0x55bdeddbaa09 <unknown>\nE       #4 0x55bdeddbc744 <unknown>\nE       #5 0x55bdeddbacbd <unknown>\nE       #6 0x55bdeddba52f <unknown>\nE       #7 0x55bdeddba422 <unknown>\nE       #8 0x55bdeddb8493 <unknown>\nE       #9 0x55bdeddb8ada <unknown>\nE       #10 0x55bdeddd4f41 <unknown>\nE       #11 0x55bdede668c5 <unknown>\nE       #12 0x55bdede46b22 <unknown>\nE       #13 0x55bdede65d7d <unknown>\nE       #14 0x55bdede468c3 <unknown>\nE       #15 0x55bdede146b3 <unknown>\nE       #16 0x55bdede1568e <unknown>\nE       #17 0x55bdee0b6a2b <unknown>\nE       #18 0x55bdee0ba9b1 <unknown>\nE       #19 0x55bdee0a3225 <unknown>\nE       #20 0x55bdee0bb532 <unknown>\nE       #21 0x55bdee08838f <unknown>\nE       #22 0x55bdee0daf28 <unknown>\nE       #23 0x55bdee0db0f3 <unknown>\nE       #24 0x55bdee0eae7c <unknown>\nE       #25 0x7fcb44694ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728781182641,
      "stop" : 1728781182641,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728781307369,
      "stop" : 1728781308146,
      "duration" : 777
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728781308146,
      "stop" : 1728781308748,
      "duration" : 602
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55bdee0ec02a <unknown>\n#1 0x55bdeddd25e0 <unknown>\n#2 0x55bdeddca7eb <unknown>\n#3 0x55bdeddbaa09 <unknown>\n#4 0x55bdeddbc744 <unknown>\n#5 0x55bdeddbacbd <unknown>\n#6 0x55bdeddba52f <unknown>\n#7 0x55bdeddba422 <unknown>\n#8 0x55bdeddb8493 <unknown>\n#9 0x55bdeddb8ada <unknown>\n#10 0x55bdeddd4f41 <unknown>\n#11 0x55bdede668c5 <unknown>\n#12 0x55bdede46b22 <unknown>\n#13 0x55bdede65d7d <unknown>\n#14 0x55bdede468c3 <unknown>\n#15 0x55bdede146b3 <unknown>\n#16 0x55bdede1568e <unknown>\n#17 0x55bdee0b6a2b <unknown>\n#18 0x55bdee0ba9b1 <unknown>\n#19 0x55bdee0a3225 <unknown>\n#20 0x55bdee0bb532 <unknown>\n#21 0x55bdee08838f <unknown>\n#22 0x55bdee0daf28 <unknown>\n#23 0x55bdee0db0f3 <unknown>\n#24 0x55bdee0eae7c <unknown>\n#25 0x7fcb44694ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728781308146,
        "stop" : 1728781308747,
        "duration" : 601
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55bdee0ec02a <unknown>\n#1 0x55bdeddd25e0 <unknown>\n#2 0x55bdeddca7eb <unknown>\n#3 0x55bdeddbaa09 <unknown>\n#4 0x55bdeddbc744 <unknown>\n#5 0x55bdeddbacbd <unknown>\n#6 0x55bdeddba52f <unknown>\n#7 0x55bdeddba422 <unknown>\n#8 0x55bdeddb8493 <unknown>\n#9 0x55bdeddb8ada <unknown>\n#10 0x55bdeddd4f41 <unknown>\n#11 0x55bdede668c5 <unknown>\n#12 0x55bdede46b22 <unknown>\n#13 0x55bdede65d7d <unknown>\n#14 0x55bdede468c3 <unknown>\n#15 0x55bdede146b3 <unknown>\n#16 0x55bdede1568e <unknown>\n#17 0x55bdee0b6a2b <unknown>\n#18 0x55bdee0ba9b1 <unknown>\n#19 0x55bdee0a3225 <unknown>\n#20 0x55bdee0bb532 <unknown>\n#21 0x55bdee08838f <unknown>\n#22 0x55bdee0daf28 <unknown>\n#23 0x55bdee0db0f3 <unknown>\n#24 0x55bdee0eae7c <unknown>\n#25 0x7fcb44694ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"c6fcd102d6deddb647beb2e30180a9dd\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728781308802,
      "stop" : 1728781308864,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Test Registration Page"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "registration_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestRegistrationPage"
  }, {
    "name" : "host",
    "value" : "fv-az585-604"
  }, {
    "name" : "thread",
    "value" : "2289-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.registration_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "birthday",
    "value" : "1981"
  }, {
    "name" : "confirm_password",
    "value" : "'password'"
  }, {
    "name" : "email",
    "value" : "''"
  }, {
    "name" : "error_message",
    "value" : "['Please enter your login and password', 'Пожалуйста, введите логин и пароль.']"
  }, {
    "name" : "first_name",
    "value" : "'Auto Test'"
  }, {
    "name" : "password",
    "value" : "'password'"
  }, {
    "name" : "title",
    "value" : "'new email and empty email'"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 1,
        "skipped" : 0,
        "passed" : 2,
        "unknown" : 0,
        "total" : 3
      },
      "items" : [ {
        "uid" : "5f415fd07ff069fd",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/135//#testresult/5f415fd07ff069fd",
        "status" : "passed",
        "time" : {
          "start" : 1727399340632,
          "stop" : 1727399341361,
          "duration" : 729
        }
      }, {
        "uid" : "84a08052543c01fe",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/48//#testresult/84a08052543c01fe",
        "status" : "passed",
        "time" : {
          "start" : 1718024187976,
          "stop" : 1718024188588,
          "duration" : 612
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "1b8ccb634f1d8804.json",
  "parameterValues" : [ "1981", "'password'", "''", "['Please enter your login and password', 'Пожалуйста, введите логин и пароль.']", "'Auto Test'", "'password'", "'new email and empty email'" ]
}