{
  "uid" : "2fda9e0a0f93018a",
  "name" : "Solutions to a random task in the \"Слова\" group and comparison of statics.",
  "fullName" : "tests.test_speech_exercises_ru.TestCardsRU#test_solve_word_cards_with_statistic_ru",
  "historyId" : "0fb6881b2015244903bd7785af7503a6",
  "time" : {
    "start" : 1728781364717,
    "stop" : 1728781364717,
    "duration" : 0
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x560c5f86602a <unknown>\n#1 0x560c5f54c5e0 <unknown>\n#2 0x560c5f5447eb <unknown>\n#3 0x560c5f534a09 <unknown>\n#4 0x560c5f536744 <unknown>\n#5 0x560c5f534cbd <unknown>\n#6 0x560c5f53452f <unknown>\n#7 0x560c5f534422 <unknown>\n#8 0x560c5f532493 <unknown>\n#9 0x560c5f532ada <unknown>\n#10 0x560c5f54ef41 <unknown>\n#11 0x560c5f5e08c5 <unknown>\n#12 0x560c5f5c0b22 <unknown>\n#13 0x560c5f5dfd7d <unknown>\n#14 0x560c5f5c08c3 <unknown>\n#15 0x560c5f58e6b3 <unknown>\n#16 0x560c5f58f68e <unknown>\n#17 0x560c5f830a2b <unknown>\n#18 0x560c5f8349b1 <unknown>\n#19 0x560c5f81d225 <unknown>\n#20 0x560c5f835532 <unknown>\n#21 0x560c5f80238f <unknown>\n#22 0x560c5f854f28 <unknown>\n#23 0x560c5f8550f3 <unknown>\n#24 0x560c5f864e7c <unknown>\n#25 0x7f715d494ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"98cf52aa3bd6b2a5de7dc16cb5bab0db\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fe0c0f1c0e0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x560c5f8550f3 \\\\u003Cunknown>\\\\n#24 0x560c5f864e7c \\\\u003Cunknown>\\\\n#25 0x7f715d494ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x560c5f86602a <unknown>\nE       #1 0x560c5f54c5e0 <unknown>\nE       #2 0x560c5f5447eb <unknown>\nE       #3 0x560c5f534a09 <unknown>\nE       #4 0x560c5f536744 <unknown>\nE       #5 0x560c5f534cbd <unknown>\nE       #6 0x560c5f53452f <unknown>\nE       #7 0x560c5f534422 <unknown>\nE       #8 0x560c5f532493 <unknown>\nE       #9 0x560c5f532ada <unknown>\nE       #10 0x560c5f54ef41 <unknown>\nE       #11 0x560c5f5e08c5 <unknown>\nE       #12 0x560c5f5c0b22 <unknown>\nE       #13 0x560c5f5dfd7d <unknown>\nE       #14 0x560c5f5c08c3 <unknown>\nE       #15 0x560c5f58e6b3 <unknown>\nE       #16 0x560c5f58f68e <unknown>\nE       #17 0x560c5f830a2b <unknown>\nE       #18 0x560c5f8349b1 <unknown>\nE       #19 0x560c5f81d225 <unknown>\nE       #20 0x560c5f835532 <unknown>\nE       #21 0x560c5f80238f <unknown>\nE       #22 0x560c5f854f28 <unknown>\nE       #23 0x560c5f8550f3 <unknown>\nE       #24 0x560c5f864e7c <unknown>\nE       #25 0x7f715d494ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728781182641,
      "stop" : 1728781182641,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728781365497,
      "stop" : 1728781366095,
      "duration" : 598
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x560c5f86602a <unknown>\n#1 0x560c5f54c5e0 <unknown>\n#2 0x560c5f5447eb <unknown>\n#3 0x560c5f534a09 <unknown>\n#4 0x560c5f536744 <unknown>\n#5 0x560c5f534cbd <unknown>\n#6 0x560c5f53452f <unknown>\n#7 0x560c5f534422 <unknown>\n#8 0x560c5f532493 <unknown>\n#9 0x560c5f532ada <unknown>\n#10 0x560c5f54ef41 <unknown>\n#11 0x560c5f5e08c5 <unknown>\n#12 0x560c5f5c0b22 <unknown>\n#13 0x560c5f5dfd7d <unknown>\n#14 0x560c5f5c08c3 <unknown>\n#15 0x560c5f58e6b3 <unknown>\n#16 0x560c5f58f68e <unknown>\n#17 0x560c5f830a2b <unknown>\n#18 0x560c5f8349b1 <unknown>\n#19 0x560c5f81d225 <unknown>\n#20 0x560c5f835532 <unknown>\n#21 0x560c5f80238f <unknown>\n#22 0x560c5f854f28 <unknown>\n#23 0x560c5f8550f3 <unknown>\n#24 0x560c5f864e7c <unknown>\n#25 0x7f715d494ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728781365497,
        "stop" : 1728781366095,
        "duration" : 598
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x560c5f86602a <unknown>\n#1 0x560c5f54c5e0 <unknown>\n#2 0x560c5f5447eb <unknown>\n#3 0x560c5f534a09 <unknown>\n#4 0x560c5f536744 <unknown>\n#5 0x560c5f534cbd <unknown>\n#6 0x560c5f53452f <unknown>\n#7 0x560c5f534422 <unknown>\n#8 0x560c5f532493 <unknown>\n#9 0x560c5f532ada <unknown>\n#10 0x560c5f54ef41 <unknown>\n#11 0x560c5f5e08c5 <unknown>\n#12 0x560c5f5c0b22 <unknown>\n#13 0x560c5f5dfd7d <unknown>\n#14 0x560c5f5c08c3 <unknown>\n#15 0x560c5f58e6b3 <unknown>\n#16 0x560c5f58f68e <unknown>\n#17 0x560c5f830a2b <unknown>\n#18 0x560c5f8349b1 <unknown>\n#19 0x560c5f81d225 <unknown>\n#20 0x560c5f835532 <unknown>\n#21 0x560c5f80238f <unknown>\n#22 0x560c5f854f28 <unknown>\n#23 0x560c5f8550f3 <unknown>\n#24 0x560c5f864e7c <unknown>\n#25 0x7f715d494ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"98cf52aa3bd6b2a5de7dc16cb5bab0db\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728781364717,
      "stop" : 1728781365497,
      "duration" : 780
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728781366130,
      "stop" : 1728781366192,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Speech exercises."
  }, {
    "name" : "suite",
    "value" : "Речевые упражнения."
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.xfail"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "subSuite",
    "value" : "TestCardsRU"
  }, {
    "name" : "host",
    "value" : "fv-az585-604"
  }, {
    "name" : "thread",
    "value" : "2289-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_speech_exercises_ru"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 0,
        "skipped" : 499,
        "passed" : 0,
        "unknown" : 0,
        "total" : 499
      },
      "items" : [ {
        "uid" : "5076af4246edd15",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/150//#testresult/5076af4246edd15",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55d43e64402a <unknown>\n#1 0x55d43e32a5e0 <unknown>\n#2 0x55d43e3227eb <unknown>\n#3 0x55d43e312a09 <unknown>\n#4 0x55d43e314744 <unknown>\n#5 0x55d43e312cbd <unknown>\n#6 0x55d43e31252f <unknown>\n#7 0x55d43e312422 <unknown>\n#8 0x55d43e310493 <unknown>\n#9 0x55d43e310ada <unknown>\n#10 0x55d43e32cf41 <unknown>\n#11 0x55d43e3be8c5 <unknown>\n#12 0x55d43e39eb22 <unknown>\n#13 0x55d43e3bdd7d <unknown>\n#14 0x55d43e39e8c3 <unknown>\n#15 0x55d43e36c6b3 <unknown>\n#16 0x55d43e36d68e <unknown>\n#17 0x55d43e60ea2b <unknown>\n#18 0x55d43e6129b1 <unknown>\n#19 0x55d43e5fb225 <unknown>\n#20 0x55d43e613532 <unknown>\n#21 0x55d43e5e038f <unknown>\n#22 0x55d43e632f28 <unknown>\n#23 0x55d43e6330f3 <unknown>\n#24 0x55d43e642e7c <unknown>\n#25 0x7fe492494ac3 <unknown>",
        "time" : {
          "start" : 1728694691417,
          "stop" : 1728694691417,
          "duration" : 0
        }
      }, {
        "uid" : "377bc5b3d4405aae",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/149//#testresult/377bc5b3d4405aae",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x558359d3002a <unknown>\n#1 0x558359a165e0 <unknown>\n#2 0x558359a0e7eb <unknown>\n#3 0x5583599fea09 <unknown>\n#4 0x558359a00744 <unknown>\n#5 0x5583599fecbd <unknown>\n#6 0x5583599fe52f <unknown>\n#7 0x5583599fe422 <unknown>\n#8 0x5583599fc493 <unknown>\n#9 0x5583599fcada <unknown>\n#10 0x558359a18f41 <unknown>\n#11 0x558359aaa8c5 <unknown>\n#12 0x558359a8ab22 <unknown>\n#13 0x558359aa9d7d <unknown>\n#14 0x558359a8a8c3 <unknown>\n#15 0x558359a586b3 <unknown>\n#16 0x558359a5968e <unknown>\n#17 0x558359cfaa2b <unknown>\n#18 0x558359cfe9b1 <unknown>\n#19 0x558359ce7225 <unknown>\n#20 0x558359cff532 <unknown>\n#21 0x558359ccc38f <unknown>\n#22 0x558359d1ef28 <unknown>\n#23 0x558359d1f0f3 <unknown>\n#24 0x558359d2ee7c <unknown>\n#25 0x7f7c83e94ac3 <unknown>",
        "time" : {
          "start" : 1728608291591,
          "stop" : 1728608291591,
          "duration" : 0
        }
      }, {
        "uid" : "aa978b5e66d3df3f",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/322//#testresult/aa978b5e66d3df3f",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 29",
        "time" : {
          "start" : 1728557867592,
          "stop" : 1728557874392,
          "duration" : 6800
        }
      }, {
        "uid" : "980d3b94e6112f3e",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/321//#testresult/980d3b94e6112f3e",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('xpath', '//a[@title=\"Речевые упражнения\"]')\nStacktrace:\n#0 0x557383dd602a <unknown>\n#1 0x557383abc5e0 <unknown>\n#2 0x557383b0bbe8 <unknown>\n#3 0x557383b0be81 <unknown>\n#4 0x557383b528c4 <unknown>\n#5 0x557383b30b4d <unknown>\n#6 0x557383b4fd7d <unknown>\n#7 0x557383b308c3 <unknown>\n#8 0x557383afe6b3 <unknown>\n#9 0x557383aff68e <unknown>\n#10 0x557383da0a2b <unknown>\n#11 0x557383da49b1 <unknown>\n#12 0x557383d8d225 <unknown>\n#13 0x557383da5532 <unknown>\n#14 0x557383d7238f <unknown>\n#15 0x557383dc4f28 <unknown>\n#16 0x557383dc50f3 <unknown>\n#17 0x557383dd4e7c <unknown>\n#18 0x7f2724694ac3 <unknown>",
        "time" : {
          "start" : 1728554754914,
          "stop" : 1728554777102,
          "duration" : 22188
        }
      }, {
        "uid" : "86aa932a016035a9",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/148//#testresult/86aa932a016035a9",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 39",
        "time" : {
          "start" : 1728522824790,
          "stop" : 1728522832108,
          "duration" : 7318
        }
      }, {
        "uid" : "86dcb93c888c5ddc",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/320//#testresult/86dcb93c888c5ddc",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 33",
        "time" : {
          "start" : 1728471109588,
          "stop" : 1728471115407,
          "duration" : 5819
        }
      }, {
        "uid" : "4926a437f90f4b3d",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/319//#testresult/4926a437f90f4b3d",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 33",
        "time" : {
          "start" : 1728468573154,
          "stop" : 1728468579390,
          "duration" : 6236
        }
      }, {
        "uid" : "5a962986cfe10c60",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/147//#testresult/5a962986cfe10c60",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 2",
        "time" : {
          "start" : 1728436549928,
          "stop" : 1728436557046,
          "duration" : 7118
        }
      }, {
        "uid" : "e1fb0f515153ac59",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/318//#testresult/e1fb0f515153ac59",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 34",
        "time" : {
          "start" : 1728378528442,
          "stop" : 1728378534870,
          "duration" : 6428
        }
      }, {
        "uid" : "b5bbb4d57294582c",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/317//#testresult/b5bbb4d57294582c",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 3",
        "time" : {
          "start" : 1728375828579,
          "stop" : 1728375836062,
          "duration" : 7483
        }
      }, {
        "uid" : "e2b16434e9b982ce",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/316//#testresult/e2b16434e9b982ce",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 7",
        "time" : {
          "start" : 1728375461238,
          "stop" : 1728375486935,
          "duration" : 25697
        }
      }, {
        "uid" : "193fb04e6a1f215c",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/146//#testresult/193fb04e6a1f215c",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 44",
        "time" : {
          "start" : 1728349550505,
          "stop" : 1728349559903,
          "duration" : 9398
        }
      }, {
        "uid" : "9adbe1e6d8e59deb",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/315//#testresult/9adbe1e6d8e59deb",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1728293564244,
          "stop" : 1728293564244,
          "duration" : 0
        }
      }, {
        "uid" : "46fc2759a9400f2d",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/314//#testresult/46fc2759a9400f2d",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1728290617649,
          "stop" : 1728290617649,
          "duration" : 0
        }
      }, {
        "uid" : "b505110fcc7930fc",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/145//#testresult/b505110fcc7930fc",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1728264261380,
          "stop" : 1728264261380,
          "duration" : 0
        }
      }, {
        "uid" : "fbd247778b42fb75",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/313//#testresult/fbd247778b42fb75",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1728227462624,
          "stop" : 1728227462624,
          "duration" : 0
        }
      }, {
        "uid" : "ecc352cc85d48acf",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/312//#testresult/ecc352cc85d48acf",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1728222536762,
          "stop" : 1728222536762,
          "duration" : 0
        }
      }, {
        "uid" : "c0d8e00a006fb53a",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/144//#testresult/c0d8e00a006fb53a",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 28",
        "time" : {
          "start" : 1728177561792,
          "stop" : 1728177568618,
          "duration" : 6826
        }
      }, {
        "uid" : "fece763014e141e",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/311//#testresult/fece763014e141e",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 27",
        "time" : {
          "start" : 1728118013461,
          "stop" : 1728118020461,
          "duration" : 7000
        }
      }, {
        "uid" : "553de8d8d4cbdc26",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/310//#testresult/553de8d8d4cbdc26",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 33",
        "time" : {
          "start" : 1728109517769,
          "stop" : 1728109524403,
          "duration" : 6634
        }
      } ]
    },
    "tags" : [ "@pytest.mark.xfail" ]
  },
  "source" : "2fda9e0a0f93018a.json",
  "parameterValues" : [ ]
}