{
  "uid" : "6cd7b07e5fe52d85",
  "name" : "Checking the possibility of authorization with incorrect data",
  "fullName" : "tests.authorisation_page_test.TestAuthorizedUserPage#test_auth_user_with_wrong_password",
  "historyId" : "4b03ea5faa5e83a4d2234cc1422bdcfd",
  "time" : {
    "start" : 1728781191645,
    "stop" : 1728781191645,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x5573715c702a <unknown>\n#1 0x5573712ad5e0 <unknown>\n#2 0x5573712a57eb <unknown>\n#3 0x557371295a09 <unknown>\n#4 0x557371297744 <unknown>\n#5 0x557371295cbd <unknown>\n#6 0x55737129552f <unknown>\n#7 0x557371295422 <unknown>\n#8 0x557371293493 <unknown>\n#9 0x557371293ada <unknown>\n#10 0x5573712aff41 <unknown>\n#11 0x5573713418c5 <unknown>\n#12 0x557371321b22 <unknown>\n#13 0x557371340d7d <unknown>\n#14 0x5573713218c3 <unknown>\n#15 0x5573712ef6b3 <unknown>\n#16 0x5573712f068e <unknown>\n#17 0x557371591a2b <unknown>\n#18 0x5573715959b1 <unknown>\n#19 0x55737157e225 <unknown>\n#20 0x557371596532 <unknown>\n#21 0x55737156338f <unknown>\n#22 0x5573715b5f28 <unknown>\n#23 0x5573715b60f3 <unknown>\n#24 0x5573715c5e7c <unknown>\n#25 0x7f1b99a94ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"1dbc594757bcc67a31b9b81ec9142897\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fe0c104ec60>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x5573715b60f3 \\\\u003Cunknown>\\\\n#24 0x5573715c5e7c \\\\u003Cunknown>\\\\n#25 0x7f1b99a94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x5573715c702a <unknown>\nE       #1 0x5573712ad5e0 <unknown>\nE       #2 0x5573712a57eb <unknown>\nE       #3 0x557371295a09 <unknown>\nE       #4 0x557371297744 <unknown>\nE       #5 0x557371295cbd <unknown>\nE       #6 0x55737129552f <unknown>\nE       #7 0x557371295422 <unknown>\nE       #8 0x557371293493 <unknown>\nE       #9 0x557371293ada <unknown>\nE       #10 0x5573712aff41 <unknown>\nE       #11 0x5573713418c5 <unknown>\nE       #12 0x557371321b22 <unknown>\nE       #13 0x557371340d7d <unknown>\nE       #14 0x5573713218c3 <unknown>\nE       #15 0x5573712ef6b3 <unknown>\nE       #16 0x5573712f068e <unknown>\nE       #17 0x557371591a2b <unknown>\nE       #18 0x5573715959b1 <unknown>\nE       #19 0x55737157e225 <unknown>\nE       #20 0x557371596532 <unknown>\nE       #21 0x55737156338f <unknown>\nE       #22 0x5573715b5f28 <unknown>\nE       #23 0x5573715b60f3 <unknown>\nE       #24 0x5573715c5e7c <unknown>\nE       #25 0x7f1b99a94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728781182641,
      "stop" : 1728781182641,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728781191646,
      "stop" : 1728781192417,
      "duration" : 771
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728781192418,
      "stop" : 1728781193017,
      "duration" : 599
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x5573715c702a <unknown>\n#1 0x5573712ad5e0 <unknown>\n#2 0x5573712a57eb <unknown>\n#3 0x557371295a09 <unknown>\n#4 0x557371297744 <unknown>\n#5 0x557371295cbd <unknown>\n#6 0x55737129552f <unknown>\n#7 0x557371295422 <unknown>\n#8 0x557371293493 <unknown>\n#9 0x557371293ada <unknown>\n#10 0x5573712aff41 <unknown>\n#11 0x5573713418c5 <unknown>\n#12 0x557371321b22 <unknown>\n#13 0x557371340d7d <unknown>\n#14 0x5573713218c3 <unknown>\n#15 0x5573712ef6b3 <unknown>\n#16 0x5573712f068e <unknown>\n#17 0x557371591a2b <unknown>\n#18 0x5573715959b1 <unknown>\n#19 0x55737157e225 <unknown>\n#20 0x557371596532 <unknown>\n#21 0x55737156338f <unknown>\n#22 0x5573715b5f28 <unknown>\n#23 0x5573715b60f3 <unknown>\n#24 0x5573715c5e7c <unknown>\n#25 0x7f1b99a94ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728781192418,
        "stop" : 1728781193016,
        "duration" : 598
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x5573715c702a <unknown>\n#1 0x5573712ad5e0 <unknown>\n#2 0x5573712a57eb <unknown>\n#3 0x557371295a09 <unknown>\n#4 0x557371297744 <unknown>\n#5 0x557371295cbd <unknown>\n#6 0x55737129552f <unknown>\n#7 0x557371295422 <unknown>\n#8 0x557371293493 <unknown>\n#9 0x557371293ada <unknown>\n#10 0x5573712aff41 <unknown>\n#11 0x5573713418c5 <unknown>\n#12 0x557371321b22 <unknown>\n#13 0x557371340d7d <unknown>\n#14 0x5573713218c3 <unknown>\n#15 0x5573712ef6b3 <unknown>\n#16 0x5573712f068e <unknown>\n#17 0x557371591a2b <unknown>\n#18 0x5573715959b1 <unknown>\n#19 0x55737157e225 <unknown>\n#20 0x557371596532 <unknown>\n#21 0x55737156338f <unknown>\n#22 0x5573715b5f28 <unknown>\n#23 0x5573715b60f3 <unknown>\n#24 0x5573715c5e7c <unknown>\n#25 0x7f1b99a94ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"1dbc594757bcc67a31b9b81ec9142897\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728781193048,
      "stop" : 1728781193110,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Test Authorized User Page"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "authorisation_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestAuthorizedUserPage"
  }, {
    "name" : "host",
    "value" : "fv-az585-604"
  }, {
    "name" : "thread",
    "value" : "2289-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.authorisation_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 6,
        "skipped" : 0,
        "passed" : 493,
        "unknown" : 0,
        "total" : 499
      },
      "items" : [ {
        "uid" : "e7774577831d670c",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/150//#testresult/e7774577831d670c",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x562df498c02a <unknown>\n#1 0x562df46725e0 <unknown>\n#2 0x562df466a7eb <unknown>\n#3 0x562df465aa09 <unknown>\n#4 0x562df465c744 <unknown>\n#5 0x562df465acbd <unknown>\n#6 0x562df465a52f <unknown>\n#7 0x562df465a422 <unknown>\n#8 0x562df4658493 <unknown>\n#9 0x562df4658ada <unknown>\n#10 0x562df4674f41 <unknown>\n#11 0x562df47068c5 <unknown>\n#12 0x562df46e6b22 <unknown>\n#13 0x562df4705d7d <unknown>\n#14 0x562df46e68c3 <unknown>\n#15 0x562df46b46b3 <unknown>\n#16 0x562df46b568e <unknown>\n#17 0x562df4956a2b <unknown>\n#18 0x562df495a9b1 <unknown>\n#19 0x562df4943225 <unknown>\n#20 0x562df495b532 <unknown>\n#21 0x562df492838f <unknown>\n#22 0x562df497af28 <unknown>\n#23 0x562df497b0f3 <unknown>\n#24 0x562df498ae7c <unknown>\n#25 0x7f90a2e94ac3 <unknown>",
        "time" : {
          "start" : 1728694513441,
          "stop" : 1728694513441,
          "duration" : 0
        }
      }, {
        "uid" : "ef1ce19614f58c6f",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/149//#testresult/ef1ce19614f58c6f",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x558b425c802a <unknown>\n#1 0x558b422ae5e0 <unknown>\n#2 0x558b422a67eb <unknown>\n#3 0x558b42296a09 <unknown>\n#4 0x558b42298744 <unknown>\n#5 0x558b42296cbd <unknown>\n#6 0x558b4229652f <unknown>\n#7 0x558b42296422 <unknown>\n#8 0x558b42294493 <unknown>\n#9 0x558b42294ada <unknown>\n#10 0x558b422b0f41 <unknown>\n#11 0x558b423428c5 <unknown>\n#12 0x558b42322b22 <unknown>\n#13 0x558b42341d7d <unknown>\n#14 0x558b423228c3 <unknown>\n#15 0x558b422f06b3 <unknown>\n#16 0x558b422f168e <unknown>\n#17 0x558b42592a2b <unknown>\n#18 0x558b425969b1 <unknown>\n#19 0x558b4257f225 <unknown>\n#20 0x558b42597532 <unknown>\n#21 0x558b4256438f <unknown>\n#22 0x558b425b6f28 <unknown>\n#23 0x558b425b70f3 <unknown>\n#24 0x558b425c6e7c <unknown>\n#25 0x7f3d41494ac3 <unknown>",
        "time" : {
          "start" : 1728608132819,
          "stop" : 1728608132819,
          "duration" : 0
        }
      }, {
        "uid" : "31c34250f1d1963b",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/322//#testresult/31c34250f1d1963b",
        "status" : "passed",
        "time" : {
          "start" : 1728556718806,
          "stop" : 1728556719681,
          "duration" : 875
        }
      }, {
        "uid" : "9142ced40ebf0e4b",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/321//#testresult/9142ced40ebf0e4b",
        "status" : "passed",
        "time" : {
          "start" : 1728553664689,
          "stop" : 1728553665613,
          "duration" : 924
        }
      }, {
        "uid" : "1fdfa593ace75053",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/148//#testresult/1fdfa593ace75053",
        "status" : "passed",
        "time" : {
          "start" : 1728521741749,
          "stop" : 1728521742665,
          "duration" : 916
        }
      }, {
        "uid" : "abed849eb33d04c6",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/320//#testresult/abed849eb33d04c6",
        "status" : "passed",
        "time" : {
          "start" : 1728470241696,
          "stop" : 1728470242623,
          "duration" : 927
        }
      }, {
        "uid" : "e7290be606d46b24",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/319//#testresult/e7290be606d46b24",
        "status" : "passed",
        "time" : {
          "start" : 1728467645395,
          "stop" : 1728467646327,
          "duration" : 932
        }
      }, {
        "uid" : "8ab6ecfb97896a6b",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/147//#testresult/8ab6ecfb97896a6b",
        "status" : "passed",
        "time" : {
          "start" : 1728435338506,
          "stop" : 1728435339462,
          "duration" : 956
        }
      }, {
        "uid" : "30565e34f3805690",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/318//#testresult/30565e34f3805690",
        "status" : "passed",
        "time" : {
          "start" : 1728377768419,
          "stop" : 1728377769340,
          "duration" : 921
        }
      }, {
        "uid" : "d339d1658e5b68df",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/317//#testresult/d339d1658e5b68df",
        "status" : "passed",
        "time" : {
          "start" : 1728374967990,
          "stop" : 1728374968908,
          "duration" : 918
        }
      }, {
        "uid" : "968c629090a3dfbd",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/316//#testresult/968c629090a3dfbd",
        "status" : "passed",
        "time" : {
          "start" : 1728374856786,
          "stop" : 1728374857702,
          "duration" : 916
        }
      }, {
        "uid" : "64ae751d4f405449",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/146//#testresult/64ae751d4f405449",
        "status" : "passed",
        "time" : {
          "start" : 1728348947114,
          "stop" : 1728348948041,
          "duration" : 927
        }
      }, {
        "uid" : "cf5089dda6b0b502",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/315//#testresult/cf5089dda6b0b502",
        "status" : "passed",
        "time" : {
          "start" : 1728292449374,
          "stop" : 1728292450290,
          "duration" : 916
        }
      }, {
        "uid" : "e6bed1f621d9cc87",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/314//#testresult/e6bed1f621d9cc87",
        "status" : "passed",
        "time" : {
          "start" : 1728289487945,
          "stop" : 1728289488881,
          "duration" : 936
        }
      }, {
        "uid" : "a21c33fbb6ed49f0",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/145//#testresult/a21c33fbb6ed49f0",
        "status" : "passed",
        "time" : {
          "start" : 1728262668508,
          "stop" : 1728262669411,
          "duration" : 903
        }
      }, {
        "uid" : "4972866d1bd76016",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/313//#testresult/4972866d1bd76016",
        "status" : "passed",
        "time" : {
          "start" : 1728225732524,
          "stop" : 1728225733402,
          "duration" : 878
        }
      }, {
        "uid" : "acd98147d8cea017",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/312//#testresult/acd98147d8cea017",
        "status" : "passed",
        "time" : {
          "start" : 1728220906747,
          "stop" : 1728220907672,
          "duration" : 925
        }
      }, {
        "uid" : "fb4052f5f3044ed9",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/144//#testresult/fb4052f5f3044ed9",
        "status" : "passed",
        "time" : {
          "start" : 1728176417496,
          "stop" : 1728176418402,
          "duration" : 906
        }
      }, {
        "uid" : "1c50bb8c970f35d7",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/311//#testresult/1c50bb8c970f35d7",
        "status" : "passed",
        "time" : {
          "start" : 1728117091958,
          "stop" : 1728117092866,
          "duration" : 908
        }
      }, {
        "uid" : "f810f6dffba23f8c",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/310//#testresult/f810f6dffba23f8c",
        "status" : "passed",
        "time" : {
          "start" : 1728108505583,
          "stop" : 1728108506504,
          "duration" : 921
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "6cd7b07e5fe52d85.json",
  "parameterValues" : [ ]
}