{
  "uid" : "bc25a24ff99b95c7",
  "name" : "Verify redirection to specialists page not authorized user.",
  "fullName" : "tests.main_page_test.TestMainPage#test_mp_05_verify_redirection_to_specialists_page",
  "historyId" : "3c31b28278473c09e9802cf34a761fb2",
  "time" : {
    "start" : 1728781288330,
    "stop" : 1728781288330,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x561f912ce02a <unknown>\n#1 0x561f90fb45e0 <unknown>\n#2 0x561f90fac7eb <unknown>\n#3 0x561f90f9ca09 <unknown>\n#4 0x561f90f9e744 <unknown>\n#5 0x561f90f9ccbd <unknown>\n#6 0x561f90f9c52f <unknown>\n#7 0x561f90f9c422 <unknown>\n#8 0x561f90f9a493 <unknown>\n#9 0x561f90f9aada <unknown>\n#10 0x561f90fb6f41 <unknown>\n#11 0x561f910488c5 <unknown>\n#12 0x561f91028b22 <unknown>\n#13 0x561f91047d7d <unknown>\n#14 0x561f910288c3 <unknown>\n#15 0x561f90ff66b3 <unknown>\n#16 0x561f90ff768e <unknown>\n#17 0x561f91298a2b <unknown>\n#18 0x561f9129c9b1 <unknown>\n#19 0x561f91285225 <unknown>\n#20 0x561f9129d532 <unknown>\n#21 0x561f9126a38f <unknown>\n#22 0x561f912bcf28 <unknown>\n#23 0x561f912bd0f3 <unknown>\n#24 0x561f912cce7c <unknown>\n#25 0x7fea6c294ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"711f0c86bac3cf62a6c914145e3f5e56\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fe0c0f50d40>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x561f912bd0f3 \\\\u003Cunknown>\\\\n#24 0x561f912cce7c \\\\u003Cunknown>\\\\n#25 0x7fea6c294ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x561f912ce02a <unknown>\nE       #1 0x561f90fb45e0 <unknown>\nE       #2 0x561f90fac7eb <unknown>\nE       #3 0x561f90f9ca09 <unknown>\nE       #4 0x561f90f9e744 <unknown>\nE       #5 0x561f90f9ccbd <unknown>\nE       #6 0x561f90f9c52f <unknown>\nE       #7 0x561f90f9c422 <unknown>\nE       #8 0x561f90f9a493 <unknown>\nE       #9 0x561f90f9aada <unknown>\nE       #10 0x561f90fb6f41 <unknown>\nE       #11 0x561f910488c5 <unknown>\nE       #12 0x561f91028b22 <unknown>\nE       #13 0x561f91047d7d <unknown>\nE       #14 0x561f910288c3 <unknown>\nE       #15 0x561f90ff66b3 <unknown>\nE       #16 0x561f90ff768e <unknown>\nE       #17 0x561f91298a2b <unknown>\nE       #18 0x561f9129c9b1 <unknown>\nE       #19 0x561f91285225 <unknown>\nE       #20 0x561f9129d532 <unknown>\nE       #21 0x561f9126a38f <unknown>\nE       #22 0x561f912bcf28 <unknown>\nE       #23 0x561f912bd0f3 <unknown>\nE       #24 0x561f912cce7c <unknown>\nE       #25 0x7fea6c294ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728781182641,
      "stop" : 1728781182641,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728781288331,
      "stop" : 1728781289107,
      "duration" : 776
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728781289108,
      "stop" : 1728781289697,
      "duration" : 589
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x561f912ce02a <unknown>\n#1 0x561f90fb45e0 <unknown>\n#2 0x561f90fac7eb <unknown>\n#3 0x561f90f9ca09 <unknown>\n#4 0x561f90f9e744 <unknown>\n#5 0x561f90f9ccbd <unknown>\n#6 0x561f90f9c52f <unknown>\n#7 0x561f90f9c422 <unknown>\n#8 0x561f90f9a493 <unknown>\n#9 0x561f90f9aada <unknown>\n#10 0x561f90fb6f41 <unknown>\n#11 0x561f910488c5 <unknown>\n#12 0x561f91028b22 <unknown>\n#13 0x561f91047d7d <unknown>\n#14 0x561f910288c3 <unknown>\n#15 0x561f90ff66b3 <unknown>\n#16 0x561f90ff768e <unknown>\n#17 0x561f91298a2b <unknown>\n#18 0x561f9129c9b1 <unknown>\n#19 0x561f91285225 <unknown>\n#20 0x561f9129d532 <unknown>\n#21 0x561f9126a38f <unknown>\n#22 0x561f912bcf28 <unknown>\n#23 0x561f912bd0f3 <unknown>\n#24 0x561f912cce7c <unknown>\n#25 0x7fea6c294ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728781289108,
        "stop" : 1728781289696,
        "duration" : 588
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x561f912ce02a <unknown>\n#1 0x561f90fb45e0 <unknown>\n#2 0x561f90fac7eb <unknown>\n#3 0x561f90f9ca09 <unknown>\n#4 0x561f90f9e744 <unknown>\n#5 0x561f90f9ccbd <unknown>\n#6 0x561f90f9c52f <unknown>\n#7 0x561f90f9c422 <unknown>\n#8 0x561f90f9a493 <unknown>\n#9 0x561f90f9aada <unknown>\n#10 0x561f90fb6f41 <unknown>\n#11 0x561f910488c5 <unknown>\n#12 0x561f91028b22 <unknown>\n#13 0x561f91047d7d <unknown>\n#14 0x561f910288c3 <unknown>\n#15 0x561f90ff66b3 <unknown>\n#16 0x561f90ff768e <unknown>\n#17 0x561f91298a2b <unknown>\n#18 0x561f9129c9b1 <unknown>\n#19 0x561f91285225 <unknown>\n#20 0x561f9129d532 <unknown>\n#21 0x561f9126a38f <unknown>\n#22 0x561f912bcf28 <unknown>\n#23 0x561f912bd0f3 <unknown>\n#24 0x561f912cce7c <unknown>\n#25 0x7fea6c294ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"711f0c86bac3cf62a6c914145e3f5e56\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728781289730,
      "stop" : 1728781289793,
      "duration" : 63
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Main Page."
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "main_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestMainPage"
  }, {
    "name" : "host",
    "value" : "fv-az585-604"
  }, {
    "name" : "thread",
    "value" : "2289-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.main_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 12,
        "skipped" : 0,
        "passed" : 487,
        "unknown" : 0,
        "total" : 499
      },
      "items" : [ {
        "uid" : "efdbef702fcd05dc",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/150//#testresult/efdbef702fcd05dc",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x562809a2502a <unknown>\n#1 0x56280970b5e0 <unknown>\n#2 0x5628097037eb <unknown>\n#3 0x5628096f3a09 <unknown>\n#4 0x5628096f5744 <unknown>\n#5 0x5628096f3cbd <unknown>\n#6 0x5628096f352f <unknown>\n#7 0x5628096f3422 <unknown>\n#8 0x5628096f1493 <unknown>\n#9 0x5628096f1ada <unknown>\n#10 0x56280970df41 <unknown>\n#11 0x56280979f8c5 <unknown>\n#12 0x56280977fb22 <unknown>\n#13 0x56280979ed7d <unknown>\n#14 0x56280977f8c3 <unknown>\n#15 0x56280974d6b3 <unknown>\n#16 0x56280974e68e <unknown>\n#17 0x5628099efa2b <unknown>\n#18 0x5628099f39b1 <unknown>\n#19 0x5628099dc225 <unknown>\n#20 0x5628099f4532 <unknown>\n#21 0x5628099c138f <unknown>\n#22 0x562809a13f28 <unknown>\n#23 0x562809a140f3 <unknown>\n#24 0x562809a23e7c <unknown>\n#25 0x7f8a42494ac3 <unknown>",
        "time" : {
          "start" : 1728694613009,
          "stop" : 1728694613009,
          "duration" : 0
        }
      }, {
        "uid" : "f6a3591c9dad9a84",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/149//#testresult/f6a3591c9dad9a84",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x560317ac602a <unknown>\n#1 0x5603177ac5e0 <unknown>\n#2 0x5603177a47eb <unknown>\n#3 0x560317794a09 <unknown>\n#4 0x560317796744 <unknown>\n#5 0x560317794cbd <unknown>\n#6 0x56031779452f <unknown>\n#7 0x560317794422 <unknown>\n#8 0x560317792493 <unknown>\n#9 0x560317792ada <unknown>\n#10 0x5603177aef41 <unknown>\n#11 0x5603178408c5 <unknown>\n#12 0x560317820b22 <unknown>\n#13 0x56031783fd7d <unknown>\n#14 0x5603178208c3 <unknown>\n#15 0x5603177ee6b3 <unknown>\n#16 0x5603177ef68e <unknown>\n#17 0x560317a90a2b <unknown>\n#18 0x560317a949b1 <unknown>\n#19 0x560317a7d225 <unknown>\n#20 0x560317a95532 <unknown>\n#21 0x560317a6238f <unknown>\n#22 0x560317ab4f28 <unknown>\n#23 0x560317ab50f3 <unknown>\n#24 0x560317ac4e7c <unknown>\n#25 0x7fb6c7694ac3 <unknown>",
        "time" : {
          "start" : 1728608221549,
          "stop" : 1728608221549,
          "duration" : 0
        }
      }, {
        "uid" : "5c41524379545ffd",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/322//#testresult/5c41524379545ffd",
        "status" : "passed",
        "time" : {
          "start" : 1728557187635,
          "stop" : 1728557188284,
          "duration" : 649
        }
      }, {
        "uid" : "fad1aa18eaca7676",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/321//#testresult/fad1aa18eaca7676",
        "status" : "passed",
        "time" : {
          "start" : 1728554076868,
          "stop" : 1728554077539,
          "duration" : 671
        }
      }, {
        "uid" : "356fc838ac79c33e",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/148//#testresult/356fc838ac79c33e",
        "status" : "passed",
        "time" : {
          "start" : 1728522057180,
          "stop" : 1728522057827,
          "duration" : 647
        }
      }, {
        "uid" : "bccaa4053350fff",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/320//#testresult/bccaa4053350fff",
        "status" : "passed",
        "time" : {
          "start" : 1728470488881,
          "stop" : 1728470489533,
          "duration" : 652
        }
      }, {
        "uid" : "e5f865534afc95dd",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/319//#testresult/e5f865534afc95dd",
        "status" : "passed",
        "time" : {
          "start" : 1728467905534,
          "stop" : 1728467906185,
          "duration" : 651
        }
      }, {
        "uid" : "504f4eca52a7c883",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/147//#testresult/504f4eca52a7c883",
        "status" : "passed",
        "time" : {
          "start" : 1728435774105,
          "stop" : 1728435774766,
          "duration" : 661
        }
      }, {
        "uid" : "47de12d9fe4e3833",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/318//#testresult/47de12d9fe4e3833",
        "status" : "passed",
        "time" : {
          "start" : 1728378006361,
          "stop" : 1728378007034,
          "duration" : 673
        }
      }, {
        "uid" : "d1d06bd80da92be1",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/317//#testresult/d1d06bd80da92be1",
        "status" : "passed",
        "time" : {
          "start" : 1728375212539,
          "stop" : 1728375213186,
          "duration" : 647
        }
      }, {
        "uid" : "c2457d1a72006015",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/316//#testresult/c2457d1a72006015",
        "status" : "passed",
        "time" : {
          "start" : 1728375097459,
          "stop" : 1728375098115,
          "duration" : 656
        }
      }, {
        "uid" : "3f98bc31e1f508f7",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/146//#testresult/3f98bc31e1f508f7",
        "status" : "passed",
        "time" : {
          "start" : 1728349181126,
          "stop" : 1728349181772,
          "duration" : 646
        }
      }, {
        "uid" : "7fff894fcecb854e",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/315//#testresult/7fff894fcecb854e",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/specialists",
        "time" : {
          "start" : 1728292795047,
          "stop" : 1728292835485,
          "duration" : 40438
        }
      }, {
        "uid" : "63ab8fcabf1fa0c",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/314//#testresult/63ab8fcabf1fa0c",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/specialists",
        "time" : {
          "start" : 1728289841628,
          "stop" : 1728289882090,
          "duration" : 40462
        }
      }, {
        "uid" : "9edf78b1943f74e5",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/145//#testresult/9edf78b1943f74e5",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/specialists",
        "time" : {
          "start" : 1728263247194,
          "stop" : 1728263287613,
          "duration" : 40419
        }
      }, {
        "uid" : "db8db0320ce9f6ec",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/313//#testresult/db8db0320ce9f6ec",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/specialists",
        "time" : {
          "start" : 1728226387079,
          "stop" : 1728226427502,
          "duration" : 40423
        }
      }, {
        "uid" : "44c9f39cfe197ef4",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/312//#testresult/44c9f39cfe197ef4",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/specialists",
        "time" : {
          "start" : 1728221506545,
          "stop" : 1728221546974,
          "duration" : 40429
        }
      }, {
        "uid" : "8a0e5d236baeccdd",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/144//#testresult/8a0e5d236baeccdd",
        "status" : "passed",
        "time" : {
          "start" : 1728176911798,
          "stop" : 1728176912973,
          "duration" : 1175
        }
      }, {
        "uid" : "19cfb928da1a47e5",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/311//#testresult/19cfb928da1a47e5",
        "status" : "passed",
        "time" : {
          "start" : 1728117547112,
          "stop" : 1728117547789,
          "duration" : 677
        }
      }, {
        "uid" : "90895861e6853b0",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/310//#testresult/90895861e6853b0",
        "status" : "passed",
        "time" : {
          "start" : 1728108932471,
          "stop" : 1728108933127,
          "duration" : 656
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "bc25a24ff99b95c7.json",
  "parameterValues" : [ ]
}