{
  "uid" : "ce251b01bbfbcaf2",
  "name" : "Verify redirection to contributors page not authorized user.",
  "fullName" : "tests.description_page_test.TestDescriptionPage#test_dp_07_verify_redirection_to_contributors_page",
  "historyId" : "85f2b35427a7bcbc7a8256ab71746c1d",
  "time" : {
    "start" : 1728781217972,
    "stop" : 1728781217972,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x563c284b202a <unknown>\n#1 0x563c281985e0 <unknown>\n#2 0x563c281907eb <unknown>\n#3 0x563c28180a09 <unknown>\n#4 0x563c28182744 <unknown>\n#5 0x563c28180cbd <unknown>\n#6 0x563c2818052f <unknown>\n#7 0x563c28180422 <unknown>\n#8 0x563c2817e493 <unknown>\n#9 0x563c2817eada <unknown>\n#10 0x563c2819af41 <unknown>\n#11 0x563c2822c8c5 <unknown>\n#12 0x563c2820cb22 <unknown>\n#13 0x563c2822bd7d <unknown>\n#14 0x563c2820c8c3 <unknown>\n#15 0x563c281da6b3 <unknown>\n#16 0x563c281db68e <unknown>\n#17 0x563c2847ca2b <unknown>\n#18 0x563c284809b1 <unknown>\n#19 0x563c28469225 <unknown>\n#20 0x563c28481532 <unknown>\n#21 0x563c2844e38f <unknown>\n#22 0x563c284a0f28 <unknown>\n#23 0x563c284a10f3 <unknown>\n#24 0x563c284b0e7c <unknown>\n#25 0x7fb46ac94ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"c6d2d17e541dbd0b3f8744b43ab84bda\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fe0c11539e0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x563c284a10f3 \\\\u003Cunknown>\\\\n#24 0x563c284b0e7c \\\\u003Cunknown>\\\\n#25 0x7fb46ac94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x563c284b202a <unknown>\nE       #1 0x563c281985e0 <unknown>\nE       #2 0x563c281907eb <unknown>\nE       #3 0x563c28180a09 <unknown>\nE       #4 0x563c28182744 <unknown>\nE       #5 0x563c28180cbd <unknown>\nE       #6 0x563c2818052f <unknown>\nE       #7 0x563c28180422 <unknown>\nE       #8 0x563c2817e493 <unknown>\nE       #9 0x563c2817eada <unknown>\nE       #10 0x563c2819af41 <unknown>\nE       #11 0x563c2822c8c5 <unknown>\nE       #12 0x563c2820cb22 <unknown>\nE       #13 0x563c2822bd7d <unknown>\nE       #14 0x563c2820c8c3 <unknown>\nE       #15 0x563c281da6b3 <unknown>\nE       #16 0x563c281db68e <unknown>\nE       #17 0x563c2847ca2b <unknown>\nE       #18 0x563c284809b1 <unknown>\nE       #19 0x563c28469225 <unknown>\nE       #20 0x563c28481532 <unknown>\nE       #21 0x563c2844e38f <unknown>\nE       #22 0x563c284a0f28 <unknown>\nE       #23 0x563c284a10f3 <unknown>\nE       #24 0x563c284b0e7c <unknown>\nE       #25 0x7fb46ac94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728781182641,
      "stop" : 1728781182641,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728781218747,
      "stop" : 1728781219340,
      "duration" : 593
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x563c284b202a <unknown>\n#1 0x563c281985e0 <unknown>\n#2 0x563c281907eb <unknown>\n#3 0x563c28180a09 <unknown>\n#4 0x563c28182744 <unknown>\n#5 0x563c28180cbd <unknown>\n#6 0x563c2818052f <unknown>\n#7 0x563c28180422 <unknown>\n#8 0x563c2817e493 <unknown>\n#9 0x563c2817eada <unknown>\n#10 0x563c2819af41 <unknown>\n#11 0x563c2822c8c5 <unknown>\n#12 0x563c2820cb22 <unknown>\n#13 0x563c2822bd7d <unknown>\n#14 0x563c2820c8c3 <unknown>\n#15 0x563c281da6b3 <unknown>\n#16 0x563c281db68e <unknown>\n#17 0x563c2847ca2b <unknown>\n#18 0x563c284809b1 <unknown>\n#19 0x563c28469225 <unknown>\n#20 0x563c28481532 <unknown>\n#21 0x563c2844e38f <unknown>\n#22 0x563c284a0f28 <unknown>\n#23 0x563c284a10f3 <unknown>\n#24 0x563c284b0e7c <unknown>\n#25 0x7fb46ac94ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728781218747,
        "stop" : 1728781219340,
        "duration" : 593
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x563c284b202a <unknown>\n#1 0x563c281985e0 <unknown>\n#2 0x563c281907eb <unknown>\n#3 0x563c28180a09 <unknown>\n#4 0x563c28182744 <unknown>\n#5 0x563c28180cbd <unknown>\n#6 0x563c2818052f <unknown>\n#7 0x563c28180422 <unknown>\n#8 0x563c2817e493 <unknown>\n#9 0x563c2817eada <unknown>\n#10 0x563c2819af41 <unknown>\n#11 0x563c2822c8c5 <unknown>\n#12 0x563c2820cb22 <unknown>\n#13 0x563c2822bd7d <unknown>\n#14 0x563c2820c8c3 <unknown>\n#15 0x563c281da6b3 <unknown>\n#16 0x563c281db68e <unknown>\n#17 0x563c2847ca2b <unknown>\n#18 0x563c284809b1 <unknown>\n#19 0x563c28469225 <unknown>\n#20 0x563c28481532 <unknown>\n#21 0x563c2844e38f <unknown>\n#22 0x563c284a0f28 <unknown>\n#23 0x563c284a10f3 <unknown>\n#24 0x563c284b0e7c <unknown>\n#25 0x7fb46ac94ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"c6d2d17e541dbd0b3f8744b43ab84bda\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728781217972,
      "stop" : 1728781218747,
      "duration" : 775
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728781219374,
      "stop" : 1728781219436,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Description Page."
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "description_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestDescriptionPage"
  }, {
    "name" : "host",
    "value" : "fv-az585-604"
  }, {
    "name" : "thread",
    "value" : "2289-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.description_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 13,
        "skipped" : 0,
        "passed" : 486,
        "unknown" : 0,
        "total" : 499
      },
      "items" : [ {
        "uid" : "1d274e873e50ed46",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/150//#testresult/1d274e873e50ed46",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x5632ee9b502a <unknown>\n#1 0x5632ee69b5e0 <unknown>\n#2 0x5632ee6937eb <unknown>\n#3 0x5632ee683a09 <unknown>\n#4 0x5632ee685744 <unknown>\n#5 0x5632ee683cbd <unknown>\n#6 0x5632ee68352f <unknown>\n#7 0x5632ee683422 <unknown>\n#8 0x5632ee681493 <unknown>\n#9 0x5632ee681ada <unknown>\n#10 0x5632ee69df41 <unknown>\n#11 0x5632ee72f8c5 <unknown>\n#12 0x5632ee70fb22 <unknown>\n#13 0x5632ee72ed7d <unknown>\n#14 0x5632ee70f8c3 <unknown>\n#15 0x5632ee6dd6b3 <unknown>\n#16 0x5632ee6de68e <unknown>\n#17 0x5632ee97fa2b <unknown>\n#18 0x5632ee9839b1 <unknown>\n#19 0x5632ee96c225 <unknown>\n#20 0x5632ee984532 <unknown>\n#21 0x5632ee95138f <unknown>\n#22 0x5632ee9a3f28 <unknown>\n#23 0x5632ee9a40f3 <unknown>\n#24 0x5632ee9b3e7c <unknown>\n#25 0x7f441ec94ac3 <unknown>",
        "time" : {
          "start" : 1728694540613,
          "stop" : 1728694540613,
          "duration" : 0
        }
      }, {
        "uid" : "787f1e4a8468d415",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/149//#testresult/787f1e4a8468d415",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55979536502a <unknown>\n#1 0x55979504b5e0 <unknown>\n#2 0x5597950437eb <unknown>\n#3 0x559795033a09 <unknown>\n#4 0x559795035744 <unknown>\n#5 0x559795033cbd <unknown>\n#6 0x55979503352f <unknown>\n#7 0x559795033422 <unknown>\n#8 0x559795031493 <unknown>\n#9 0x559795031ada <unknown>\n#10 0x55979504df41 <unknown>\n#11 0x5597950df8c5 <unknown>\n#12 0x5597950bfb22 <unknown>\n#13 0x5597950ded7d <unknown>\n#14 0x5597950bf8c3 <unknown>\n#15 0x55979508d6b3 <unknown>\n#16 0x55979508e68e <unknown>\n#17 0x55979532fa2b <unknown>\n#18 0x5597953339b1 <unknown>\n#19 0x55979531c225 <unknown>\n#20 0x559795334532 <unknown>\n#21 0x55979530138f <unknown>\n#22 0x559795353f28 <unknown>\n#23 0x5597953540f3 <unknown>\n#24 0x559795363e7c <unknown>\n#25 0x7f6213894ac3 <unknown>",
        "time" : {
          "start" : 1728608157023,
          "stop" : 1728608157023,
          "duration" : 0
        }
      }, {
        "uid" : "fbb257eb554aff47",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/322//#testresult/fbb257eb554aff47",
        "status" : "passed",
        "time" : {
          "start" : 1728556825461,
          "stop" : 1728556826118,
          "duration" : 657
        }
      }, {
        "uid" : "1e2dac863e8208c7",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/321//#testresult/1e2dac863e8208c7",
        "status" : "passed",
        "time" : {
          "start" : 1728553758365,
          "stop" : 1728553759048,
          "duration" : 683
        }
      }, {
        "uid" : "9ae3cc2133cb324c",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/148//#testresult/9ae3cc2133cb324c",
        "status" : "passed",
        "time" : {
          "start" : 1728521851822,
          "stop" : 1728521852477,
          "duration" : 655
        }
      }, {
        "uid" : "357f831486523f93",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/320//#testresult/357f831486523f93",
        "status" : "passed",
        "time" : {
          "start" : 1728470328632,
          "stop" : 1728470329308,
          "duration" : 676
        }
      }, {
        "uid" : "efe5d98540091432",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/319//#testresult/efe5d98540091432",
        "status" : "passed",
        "time" : {
          "start" : 1728467736418,
          "stop" : 1728467737085,
          "duration" : 667
        }
      }, {
        "uid" : "f8d38447bee7a78f",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/147//#testresult/f8d38447bee7a78f",
        "status" : "passed",
        "time" : {
          "start" : 1728435449847,
          "stop" : 1728435450510,
          "duration" : 663
        }
      }, {
        "uid" : "1c0299f2ee23d3f1",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/318//#testresult/1c0299f2ee23d3f1",
        "status" : "passed",
        "time" : {
          "start" : 1728377853176,
          "stop" : 1728377853840,
          "duration" : 664
        }
      }, {
        "uid" : "3f17007d28dd9a58",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/317//#testresult/3f17007d28dd9a58",
        "status" : "passed",
        "time" : {
          "start" : 1728375054500,
          "stop" : 1728375055151,
          "duration" : 651
        }
      }, {
        "uid" : "49d34232845f6913",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/316//#testresult/49d34232845f6913",
        "status" : "passed",
        "time" : {
          "start" : 1728374943010,
          "stop" : 1728374943685,
          "duration" : 675
        }
      }, {
        "uid" : "1128753403a94b09",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/146//#testresult/1128753403a94b09",
        "status" : "passed",
        "time" : {
          "start" : 1728349035253,
          "stop" : 1728349035910,
          "duration" : 657
        }
      }, {
        "uid" : "a229dfd635e5136f",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/315//#testresult/a229dfd635e5136f",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/contributors",
        "time" : {
          "start" : 1728292574954,
          "stop" : 1728292615377,
          "duration" : 40423
        }
      }, {
        "uid" : "74e7bb3f8f085012",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/314//#testresult/74e7bb3f8f085012",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/contributors",
        "time" : {
          "start" : 1728289616261,
          "stop" : 1728289656731,
          "duration" : 40470
        }
      }, {
        "uid" : "977d5e3797641ed1",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/145//#testresult/977d5e3797641ed1",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/contributors",
        "time" : {
          "start" : 1728263023178,
          "stop" : 1728263063587,
          "duration" : 40409
        }
      }, {
        "uid" : "6cf0e98f166ba53a",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/313//#testresult/6cf0e98f166ba53a",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/contributors",
        "time" : {
          "start" : 1728226123460,
          "stop" : 1728226163907,
          "duration" : 40447
        }
      }, {
        "uid" : "aa3eeb493d7dea02",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/312//#testresult/aa3eeb493d7dea02",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/contributors",
        "time" : {
          "start" : 1728221272765,
          "stop" : 1728221313204,
          "duration" : 40439
        }
      }, {
        "uid" : "bd8333e5d8f72f0f",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/144//#testresult/bd8333e5d8f72f0f",
        "status" : "passed",
        "time" : {
          "start" : 1728176570558,
          "stop" : 1728176571227,
          "duration" : 669
        }
      }, {
        "uid" : "16ebe8a547077497",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/311//#testresult/16ebe8a547077497",
        "status" : "passed",
        "time" : {
          "start" : 1728117240940,
          "stop" : 1728117241624,
          "duration" : 684
        }
      }, {
        "uid" : "a71c553081dd630e",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/310//#testresult/a71c553081dd630e",
        "status" : "passed",
        "time" : {
          "start" : 1728108644829,
          "stop" : 1728108645503,
          "duration" : 674
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "ce251b01bbfbcaf2.json",
  "parameterValues" : [ ]
}