{
  "uid" : "64e4f2a8ddc60f15",
  "name" : "Verify presence, visibility of links, buttons in the Header for an unauthorized user",
  "fullName" : "tests.header_test.TestHeaderPageStructure#test_hp_01_03_01_verify_unauth_header_structural_elements",
  "historyId" : "b2c1178ba3db93d244e484ac3e18aba2",
  "time" : {
    "start" : 1726582309939,
    "stop" : 1726582309939,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_SSL_SERVER_CERT_BAD_FORMAT\n  (Session info: chrome=128.0.6613.119)\nStacktrace:\n#0 0x55eceb7be86a <unknown>\n#1 0x55eceb48ce50 <unknown>\n#2 0x55eceb485011 <unknown>\n#3 0x55eceb4750e9 <unknown>\n#4 0x55eceb476e54 <unknown>\n#5 0x55eceb47539d <unknown>\n#6 0x55eceb474c1c <unknown>\n#7 0x55eceb474b0d <unknown>\n#8 0x55eceb472b11 <unknown>\n#9 0x55eceb4731aa <unknown>\n#10 0x55eceb48f771 <unknown>\n#11 0x55eceb520515 <unknown>\n#12 0x55eceb501492 <unknown>\n#13 0x55eceb51f9c6 <unknown>\n#14 0x55eceb501233 <unknown>\n#15 0x55eceb4cf093 <unknown>\n#16 0x55eceb4d009e <unknown>\n#17 0x55eceb785acb <unknown>\n#18 0x55eceb789a81 <unknown>\n#19 0x55eceb771695 <unknown>\n#20 0x55eceb78a5f2 <unknown>\n#21 0x55eceb75686f <unknown>\n#22 0x55eceb7ad668 <unknown>\n#23 0x55eceb7ad832 <unknown>\n#24 0x55eceb7bd65c <unknown>\n#25 0x7fbf9be94ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"c4c25462e5b4b0685a726a7d440afbf5\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f7d7761b800>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_SSL_SERVER_CERT_BAD_FOR...\\\\n#23 0x55eceb7ad832 \\\\u003Cunknown>\\\\n#24 0x55eceb7bd65c \\\\u003Cunknown>\\\\n#25 0x7fbf9be94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_SSL_SERVER_CERT_BAD_FORMAT\nE         (Session info: chrome=128.0.6613.119)\nE       Stacktrace:\nE       #0 0x55eceb7be86a <unknown>\nE       #1 0x55eceb48ce50 <unknown>\nE       #2 0x55eceb485011 <unknown>\nE       #3 0x55eceb4750e9 <unknown>\nE       #4 0x55eceb476e54 <unknown>\nE       #5 0x55eceb47539d <unknown>\nE       #6 0x55eceb474c1c <unknown>\nE       #7 0x55eceb474b0d <unknown>\nE       #8 0x55eceb472b11 <unknown>\nE       #9 0x55eceb4731aa <unknown>\nE       #10 0x55eceb48f771 <unknown>\nE       #11 0x55eceb520515 <unknown>\nE       #12 0x55eceb501492 <unknown>\nE       #13 0x55eceb51f9c6 <unknown>\nE       #14 0x55eceb501233 <unknown>\nE       #15 0x55eceb4cf093 <unknown>\nE       #16 0x55eceb4d009e <unknown>\nE       #17 0x55eceb785acb <unknown>\nE       #18 0x55eceb789a81 <unknown>\nE       #19 0x55eceb771695 <unknown>\nE       #20 0x55eceb78a5f2 <unknown>\nE       #21 0x55eceb75686f <unknown>\nE       #22 0x55eceb7ad668 <unknown>\nE       #23 0x55eceb7ad832 <unknown>\nE       #24 0x55eceb7bd65c <unknown>\nE       #25 0x7fbf9be94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1726582211375,
      "stop" : 1726582211375,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1726582309939,
      "stop" : 1726582310702,
      "duration" : 763
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1726582310703,
      "stop" : 1726582311911,
      "duration" : 1208
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_SSL_SERVER_CERT_BAD_FORMAT\n  (Session info: chrome=128.0.6613.119)\nStacktrace:\n#0 0x55eceb7be86a <unknown>\n#1 0x55eceb48ce50 <unknown>\n#2 0x55eceb485011 <unknown>\n#3 0x55eceb4750e9 <unknown>\n#4 0x55eceb476e54 <unknown>\n#5 0x55eceb47539d <unknown>\n#6 0x55eceb474c1c <unknown>\n#7 0x55eceb474b0d <unknown>\n#8 0x55eceb472b11 <unknown>\n#9 0x55eceb4731aa <unknown>\n#10 0x55eceb48f771 <unknown>\n#11 0x55eceb520515 <unknown>\n#12 0x55eceb501492 <unknown>\n#13 0x55eceb51f9c6 <unknown>\n#14 0x55eceb501233 <unknown>\n#15 0x55eceb4cf093 <unknown>\n#16 0x55eceb4d009e <unknown>\n#17 0x55eceb785acb <unknown>\n#18 0x55eceb789a81 <unknown>\n#19 0x55eceb771695 <unknown>\n#20 0x55eceb78a5f2 <unknown>\n#21 0x55eceb75686f <unknown>\n#22 0x55eceb7ad668 <unknown>\n#23 0x55eceb7ad832 <unknown>\n#24 0x55eceb7bd65c <unknown>\n#25 0x7fbf9be94ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1726582310703,
        "stop" : 1726582311911,
        "duration" : 1208
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_SSL_SERVER_CERT_BAD_FORMAT\n  (Session info: chrome=128.0.6613.119)\nStacktrace:\n#0 0x55eceb7be86a <unknown>\n#1 0x55eceb48ce50 <unknown>\n#2 0x55eceb485011 <unknown>\n#3 0x55eceb4750e9 <unknown>\n#4 0x55eceb476e54 <unknown>\n#5 0x55eceb47539d <unknown>\n#6 0x55eceb474c1c <unknown>\n#7 0x55eceb474b0d <unknown>\n#8 0x55eceb472b11 <unknown>\n#9 0x55eceb4731aa <unknown>\n#10 0x55eceb48f771 <unknown>\n#11 0x55eceb520515 <unknown>\n#12 0x55eceb501492 <unknown>\n#13 0x55eceb51f9c6 <unknown>\n#14 0x55eceb501233 <unknown>\n#15 0x55eceb4cf093 <unknown>\n#16 0x55eceb4d009e <unknown>\n#17 0x55eceb785acb <unknown>\n#18 0x55eceb789a81 <unknown>\n#19 0x55eceb771695 <unknown>\n#20 0x55eceb78a5f2 <unknown>\n#21 0x55eceb75686f <unknown>\n#22 0x55eceb7ad668 <unknown>\n#23 0x55eceb7ad832 <unknown>\n#24 0x55eceb7bd65c <unknown>\n#25 0x7fbf9be94ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"c4c25462e5b4b0685a726a7d440afbf5\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1726582311943,
      "stop" : 1726582312006,
      "duration" : 63
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Test Header"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "header_test"
  }, {
    "name" : "subSuite",
    "value" : "TestHeaderPage"
  }, {
    "name" : "host",
    "value" : "fv-az1535-406"
  }, {
    "name" : "thread",
    "value" : "2301-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.header_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 1,
        "skipped" : 0,
        "passed" : 9,
        "unknown" : 0,
        "total" : 10
      },
      "items" : [ {
        "uid" : "8ddc7f6a62bd635a",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/273//#testresult/8ddc7f6a62bd635a",
        "status" : "passed",
        "time" : {
          "start" : 1726568752926,
          "stop" : 1726568753279,
          "duration" : 353
        }
      }, {
        "uid" : "52abb9aad1ed847f",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/272//#testresult/52abb9aad1ed847f",
        "status" : "passed",
        "time" : {
          "start" : 1726560711254,
          "stop" : 1726560711619,
          "duration" : 365
        }
      }, {
        "uid" : "5a79aa95ed28bb2b",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/271//#testresult/5a79aa95ed28bb2b",
        "status" : "passed",
        "time" : {
          "start" : 1726559154571,
          "stop" : 1726559154902,
          "duration" : 331
        }
      }, {
        "uid" : "8c59c1be16c1ccaf",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/125//#testresult/8c59c1be16c1ccaf",
        "status" : "passed",
        "time" : {
          "start" : 1726534048741,
          "stop" : 1726534049085,
          "duration" : 344
        }
      }, {
        "uid" : "f61e821747c8cf2d",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/270//#testresult/f61e821747c8cf2d",
        "status" : "passed",
        "time" : {
          "start" : 1726474924860,
          "stop" : 1726474925209,
          "duration" : 349
        }
      }, {
        "uid" : "3d51d924fd743f38",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/269//#testresult/3d51d924fd743f38",
        "status" : "passed",
        "time" : {
          "start" : 1726472871031,
          "stop" : 1726472871371,
          "duration" : 340
        }
      }, {
        "uid" : "8edd7f1e6d2d8a64",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/124//#testresult/8edd7f1e6d2d8a64",
        "status" : "passed",
        "time" : {
          "start" : 1726448472606,
          "stop" : 1726448472972,
          "duration" : 366
        }
      }, {
        "uid" : "606a881980f47cd9",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/268//#testresult/606a881980f47cd9",
        "status" : "passed",
        "time" : {
          "start" : 1726386818894,
          "stop" : 1726386819240,
          "duration" : 346
        }
      }, {
        "uid" : "e8e2ed12f3d84e07",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/267//#testresult/e8e2ed12f3d84e07",
        "status" : "passed",
        "time" : {
          "start" : 1726384566327,
          "stop" : 1726384566671,
          "duration" : 344
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "64e4f2a8ddc60f15.json",
  "parameterValues" : [ ]
}