{
  "uid" : "9e15f6ac905d3c28",
  "name" : "test_registration_negative[new email and empty email-Auto Test-1928--password-password-error_message5]",
  "fullName" : "tests.registration_page_test.TestRegistrationPage#test_registration_negative",
  "historyId" : "256da5f307f8aaaf1a1a1d1f16cafc0d",
  "time" : {
    "start" : 1726582370276,
    "stop" : 1726582370276,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_SSL_SERVER_CERT_BAD_FORMAT\n  (Session info: chrome=128.0.6613.119)\nStacktrace:\n#0 0x55fc65a1586a <unknown>\n#1 0x55fc656e3e50 <unknown>\n#2 0x55fc656dc011 <unknown>\n#3 0x55fc656cc0e9 <unknown>\n#4 0x55fc656cde54 <unknown>\n#5 0x55fc656cc39d <unknown>\n#6 0x55fc656cbc1c <unknown>\n#7 0x55fc656cbb0d <unknown>\n#8 0x55fc656c9b11 <unknown>\n#9 0x55fc656ca1aa <unknown>\n#10 0x55fc656e6771 <unknown>\n#11 0x55fc65777515 <unknown>\n#12 0x55fc65758492 <unknown>\n#13 0x55fc657769c6 <unknown>\n#14 0x55fc65758233 <unknown>\n#15 0x55fc65726093 <unknown>\n#16 0x55fc6572709e <unknown>\n#17 0x55fc659dcacb <unknown>\n#18 0x55fc659e0a81 <unknown>\n#19 0x55fc659c8695 <unknown>\n#20 0x55fc659e15f2 <unknown>\n#21 0x55fc659ad86f <unknown>\n#22 0x55fc65a04668 <unknown>\n#23 0x55fc65a04832 <unknown>\n#24 0x55fc65a1465c <unknown>\n#25 0x7ff870894ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"d4668dca85f3055e19d8a0a813947cbf\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f7d775d5520>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_SSL_SERVER_CERT_BAD_FOR...\\\\n#23 0x55fc65a04832 \\\\u003Cunknown>\\\\n#24 0x55fc65a1465c \\\\u003Cunknown>\\\\n#25 0x7ff870894ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_SSL_SERVER_CERT_BAD_FORMAT\nE         (Session info: chrome=128.0.6613.119)\nE       Stacktrace:\nE       #0 0x55fc65a1586a <unknown>\nE       #1 0x55fc656e3e50 <unknown>\nE       #2 0x55fc656dc011 <unknown>\nE       #3 0x55fc656cc0e9 <unknown>\nE       #4 0x55fc656cde54 <unknown>\nE       #5 0x55fc656cc39d <unknown>\nE       #6 0x55fc656cbc1c <unknown>\nE       #7 0x55fc656cbb0d <unknown>\nE       #8 0x55fc656c9b11 <unknown>\nE       #9 0x55fc656ca1aa <unknown>\nE       #10 0x55fc656e6771 <unknown>\nE       #11 0x55fc65777515 <unknown>\nE       #12 0x55fc65758492 <unknown>\nE       #13 0x55fc657769c6 <unknown>\nE       #14 0x55fc65758233 <unknown>\nE       #15 0x55fc65726093 <unknown>\nE       #16 0x55fc6572709e <unknown>\nE       #17 0x55fc659dcacb <unknown>\nE       #18 0x55fc659e0a81 <unknown>\nE       #19 0x55fc659c8695 <unknown>\nE       #20 0x55fc659e15f2 <unknown>\nE       #21 0x55fc659ad86f <unknown>\nE       #22 0x55fc65a04668 <unknown>\nE       #23 0x55fc65a04832 <unknown>\nE       #24 0x55fc65a1465c <unknown>\nE       #25 0x7ff870894ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1726582211375,
      "stop" : 1726582211375,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1726582370276,
      "stop" : 1726582371049,
      "duration" : 773
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1726582371049,
      "stop" : 1726582372255,
      "duration" : 1206
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_SSL_SERVER_CERT_BAD_FORMAT\n  (Session info: chrome=128.0.6613.119)\nStacktrace:\n#0 0x55fc65a1586a <unknown>\n#1 0x55fc656e3e50 <unknown>\n#2 0x55fc656dc011 <unknown>\n#3 0x55fc656cc0e9 <unknown>\n#4 0x55fc656cde54 <unknown>\n#5 0x55fc656cc39d <unknown>\n#6 0x55fc656cbc1c <unknown>\n#7 0x55fc656cbb0d <unknown>\n#8 0x55fc656c9b11 <unknown>\n#9 0x55fc656ca1aa <unknown>\n#10 0x55fc656e6771 <unknown>\n#11 0x55fc65777515 <unknown>\n#12 0x55fc65758492 <unknown>\n#13 0x55fc657769c6 <unknown>\n#14 0x55fc65758233 <unknown>\n#15 0x55fc65726093 <unknown>\n#16 0x55fc6572709e <unknown>\n#17 0x55fc659dcacb <unknown>\n#18 0x55fc659e0a81 <unknown>\n#19 0x55fc659c8695 <unknown>\n#20 0x55fc659e15f2 <unknown>\n#21 0x55fc659ad86f <unknown>\n#22 0x55fc65a04668 <unknown>\n#23 0x55fc65a04832 <unknown>\n#24 0x55fc65a1465c <unknown>\n#25 0x7ff870894ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1726582371050,
        "stop" : 1726582372254,
        "duration" : 1204
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_SSL_SERVER_CERT_BAD_FORMAT\n  (Session info: chrome=128.0.6613.119)\nStacktrace:\n#0 0x55fc65a1586a <unknown>\n#1 0x55fc656e3e50 <unknown>\n#2 0x55fc656dc011 <unknown>\n#3 0x55fc656cc0e9 <unknown>\n#4 0x55fc656cde54 <unknown>\n#5 0x55fc656cc39d <unknown>\n#6 0x55fc656cbc1c <unknown>\n#7 0x55fc656cbb0d <unknown>\n#8 0x55fc656c9b11 <unknown>\n#9 0x55fc656ca1aa <unknown>\n#10 0x55fc656e6771 <unknown>\n#11 0x55fc65777515 <unknown>\n#12 0x55fc65758492 <unknown>\n#13 0x55fc657769c6 <unknown>\n#14 0x55fc65758233 <unknown>\n#15 0x55fc65726093 <unknown>\n#16 0x55fc6572709e <unknown>\n#17 0x55fc659dcacb <unknown>\n#18 0x55fc659e0a81 <unknown>\n#19 0x55fc659c8695 <unknown>\n#20 0x55fc659e15f2 <unknown>\n#21 0x55fc659ad86f <unknown>\n#22 0x55fc65a04668 <unknown>\n#23 0x55fc65a04832 <unknown>\n#24 0x55fc65a1465c <unknown>\n#25 0x7ff870894ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"d4668dca85f3055e19d8a0a813947cbf\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1726582372285,
      "stop" : 1726582372347,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Test Registration Page"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "registration_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestRegistrationPage"
  }, {
    "name" : "host",
    "value" : "fv-az1535-406"
  }, {
    "name" : "thread",
    "value" : "2301-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.registration_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "birthday",
    "value" : "1928"
  }, {
    "name" : "confirm_password",
    "value" : "'password'"
  }, {
    "name" : "email",
    "value" : "''"
  }, {
    "name" : "error_message",
    "value" : "['Please enter your login and password', 'Пожалуйста, введите логин и пароль.']"
  }, {
    "name" : "first_name",
    "value" : "'Auto Test'"
  }, {
    "name" : "password",
    "value" : "'password'"
  }, {
    "name" : "title",
    "value" : "'new email and empty email'"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 1,
        "skipped" : 0,
        "passed" : 4,
        "unknown" : 0,
        "total" : 5
      },
      "items" : [ {
        "uid" : "77e4389e3e4e7363",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/235//#testresult/77e4389e3e4e7363",
        "status" : "passed",
        "time" : {
          "start" : 1725265472058,
          "stop" : 1725265472711,
          "duration" : 653
        }
      }, {
        "uid" : "85ab517eae624045",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/44//#testresult/85ab517eae624045",
        "status" : "passed",
        "time" : {
          "start" : 1719536245180,
          "stop" : 1719536245782,
          "duration" : 602
        }
      }, {
        "uid" : "e7ef80b17ebb6c53",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/25//#testresult/e7ef80b17ebb6c53",
        "status" : "passed",
        "time" : {
          "start" : 1717150984124,
          "stop" : 1717150984735,
          "duration" : 611
        }
      }, {
        "uid" : "e55b6cf6008e6e04",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/18//#testresult/e55b6cf6008e6e04",
        "status" : "passed",
        "time" : {
          "start" : 1716888727943,
          "stop" : 1716888728543,
          "duration" : 600
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "9e15f6ac905d3c28.json",
  "parameterValues" : [ "1928", "'password'", "''", "['Please enter your login and password', 'Пожалуйста, введите логин и пароль.']", "'Auto Test'", "'password'", "'new email and empty email'" ]
}