{
  "uid" : "c843ba76a76d6cea",
  "name" : "Verify if links on the 'ru' local lead to correct pages after clicking",
  "fullName" : "tests.groups_page_test.TestGroupsPageLinks#test_gp_03_05_verify_ru_links_lead_to_proper_pages",
  "historyId" : "779545ead3b7251d45a98aa7243562c3",
  "time" : {
    "start" : 1751520971790,
    "stop" : 1751520971790,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://www.brainup.site/groups",
  "statusTrace" : "self = <pages.base_page.BasePage object at 0x7f112fa174d0>\nurl = 'https://www.brainup.site/groups'\n\n    def check_expected_link(self, url):\n        with allure.step(f'Check url is present: {url}'):\n            try:\n>               return Wait(self.driver, self.timeout).until(\n                    EC.url_to_be(url), message=f\"Can't find element by locator {url}\")\n\npages/base_page.py:80: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"9c638bb5294f48470ece4c62b601f024\")>\nmethod = <function url_to_be.<locals>._predicate at 0x7f112f7498a0>\nmessage = \"Can't find element by locator https://www.brainup.site/groups\"\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://www.brainup.site/groups\n\n/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9c638bb5294f48470ece4c62b601f024\")>\nmain_page_open = None\n\n    @pytest.fixture()\n    @allure.step('Auto test user authorized')\n    def auto_test_user_authorized(driver, main_page_open):\n        page = BasePage(driver)\n        page.element_is_present_and_clickable(MainPageLocators.LOGIN_BUTTON).click()\n        print(\"Current URL:\", driver.current_url)  # Temporarily for debugging\n        page.element_is_visible(LoginPageLocators.INPUT_LOGIN).send_keys(os.environ[\"LOGIN\"])\n        page.element_is_visible(LoginPageLocators.INPUT_PASSWORD).send_keys(os.environ[\"PASSWORD\"])\n        page.element_is_present_and_clickable(LoginPageLocators.SIGN_IN_BUTTON).click()\n>       page.check_expected_link(MainPageLinks.URL_GROUPS_PAGE)\n\ntests/conftest.py:157: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/base_page.py:84: in check_expected_link\n    return Wait(self.driver, self.timeout).until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"9c638bb5294f48470ece4c62b601f024\")>\nmethod = <function url_to_be.<locals>._predicate at 0x7f112f749ee0>\nmessage = \"Can't find element by locator https://www.brainup.site/groups\"\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://www.brainup.site/groups\n\n/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1751520187154,
      "stop" : 1751520187155,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1751520972619,
      "stop" : 1751520975425,
      "duration" : 2806
    },
    "status" : "passed",
    "steps" : [ {
      "name" : "Open page: https://www.brainup.site/",
      "time" : {
        "start" : 1751520972619,
        "stop" : 1751520975425,
        "duration" : 2806
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"9c638bb5294f48470ece4c62b601f024\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "auto_test_user_authorized",
    "time" : {
      "start" : 1751520975425,
      "stop" : 1751520995992,
      "duration" : 20567
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://www.brainup.site/groups\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 157, in auto_test_user_authorized\n    page.check_expected_link(MainPageLinks.URL_GROUPS_PAGE)\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/pages/base_page.py\", line 84, in check_expected_link\n    return Wait(self.driver, self.timeout).until(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Auto test user authorized",
      "time" : {
        "start" : 1751520975425,
        "stop" : 1751520995992,
        "duration" : 20567
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://www.brainup.site/groups\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 157, in auto_test_user_authorized\n    page.check_expected_link(MainPageLinks.URL_GROUPS_PAGE)\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/pages/base_page.py\", line 84, in check_expected_link\n    return Wait(self.driver, self.timeout).until(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n",
      "steps" : [ {
        "name" : "Check url is present: https://www.brainup.site/groups",
        "time" : {
          "start" : 1751520975850,
          "stop" : 1751520995992,
          "duration" : 20142
        },
        "status" : "broken",
        "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://www.brainup.site/groups\n\n",
        "statusTrace" : "  File \"/home/runner/work/auto-tests-python/auto-tests-python/pages/base_page.py\", line 84, in check_expected_link\n    return Wait(self.driver, self.timeout).until(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n",
        "steps" : [ ],
        "attachments" : [ ],
        "parameters" : [ ],
        "stepsCount" : 0,
        "attachmentsCount" : 0,
        "shouldDisplayMessage" : true,
        "hasContent" : true
      } ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"9c638bb5294f48470ece4c62b601f024\")>"
      }, {
        "name" : "main_page_open",
        "value" : "None"
      } ],
      "stepsCount" : 1,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 2,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1751520971791,
      "stop" : 1751520972618,
      "duration" : 827
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1751520996009,
      "stop" : 1751520996075,
      "duration" : 66
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "The Groups Page"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "groups_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestGroupsPage"
  }, {
    "name" : "host",
    "value" : "pkrvmbietmlfzoi"
  }, {
    "name" : "thread",
    "value" : "2577-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.groups_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 1,
        "skipped" : 0,
        "passed" : 14,
        "unknown" : 0,
        "total" : 15
      },
      "items" : [ {
        "uid" : "4296c7e60327c6c8",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/617//#testresult/4296c7e60327c6c8",
        "status" : "passed",
        "time" : {
          "start" : 1751458366948,
          "stop" : 1751458370496,
          "duration" : 3548
        }
      }, {
        "uid" : "35ca0c69d2f39905",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/616//#testresult/35ca0c69d2f39905",
        "status" : "passed",
        "time" : {
          "start" : 1751381367440,
          "stop" : 1751381370915,
          "duration" : 3475
        }
      }, {
        "uid" : "f800884c770a17db",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/615//#testresult/f800884c770a17db",
        "status" : "passed",
        "time" : {
          "start" : 1751368819766,
          "stop" : 1751368823068,
          "duration" : 3302
        }
      }, {
        "uid" : "ebbd9834dc7dec7",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/412//#testresult/ebbd9834dc7dec7",
        "status" : "passed",
        "time" : {
          "start" : 1751333267481,
          "stop" : 1751333270803,
          "duration" : 3322
        }
      }, {
        "uid" : "7c1e86a1639173e7",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/614//#testresult/7c1e86a1639173e7",
        "status" : "passed",
        "time" : {
          "start" : 1751275400199,
          "stop" : 1751275403492,
          "duration" : 3293
        }
      }, {
        "uid" : "657456b191364c",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/411//#testresult/657456b191364c",
        "status" : "passed",
        "time" : {
          "start" : 1751246667469,
          "stop" : 1751246670760,
          "duration" : 3291
        }
      }, {
        "uid" : "a660dcb9967023c1",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/613//#testresult/a660dcb9967023c1",
        "status" : "passed",
        "time" : {
          "start" : 1751200705645,
          "stop" : 1751200709465,
          "duration" : 3820
        }
      }, {
        "uid" : "ee9dad406a2810c2",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/410//#testresult/ee9dad406a2810c2",
        "status" : "passed",
        "time" : {
          "start" : 1751160487467,
          "stop" : 1751160490776,
          "duration" : 3309
        }
      }, {
        "uid" : "73b0f118b118cc4e",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/612//#testresult/73b0f118b118cc4e",
        "status" : "passed",
        "time" : {
          "start" : 1751089814586,
          "stop" : 1751089817898,
          "duration" : 3312
        }
      }, {
        "uid" : "dfe85d578fa287aa",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/409//#testresult/dfe85d578fa287aa",
        "status" : "passed",
        "time" : {
          "start" : 1751073515961,
          "stop" : 1751073523235,
          "duration" : 7274
        }
      }, {
        "uid" : "b29c2be6b99ab3a4",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/611//#testresult/b29c2be6b99ab3a4",
        "status" : "passed",
        "time" : {
          "start" : 1751022717760,
          "stop" : 1751022721568,
          "duration" : 3808
        }
      }, {
        "uid" : "268e5d2b7e2d11bb",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/408//#testresult/268e5d2b7e2d11bb",
        "status" : "passed",
        "time" : {
          "start" : 1750987506672,
          "stop" : 1750987513948,
          "duration" : 7276
        }
      }, {
        "uid" : "aabd2f63c6317482",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/610//#testresult/aabd2f63c6317482",
        "status" : "passed",
        "time" : {
          "start" : 1750932218010,
          "stop" : 1750932225343,
          "duration" : 7333
        }
      }, {
        "uid" : "ce223a37cd9606fc",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/609//#testresult/ce223a37cd9606fc",
        "status" : "passed",
        "time" : {
          "start" : 1750852120785,
          "stop" : 1750852128073,
          "duration" : 7288
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "c843ba76a76d6cea.json",
  "parameterValues" : [ ]
}